AddSamavrtta('﻿﻿anīcakam', ' L G L L L L L L L L L G ')
AddSamavrtta('līlā', ' L L L L G G L G L ')
AddSamavrtta('pratibhādarśanam', ' L L G G L L G G L L L L G G ')
AddSamavrtta('karṇapālikā', ' G L G L G G L G L G ')
AddSamavrtta('utkaṭapaṭṭikā', ' G G L L G L G L G L G L L L L L L G G L G G L G ')
AddSamavrtta('sindhurayā', ' G L L G G G ')
AddSamavrtta('vyāyogavatī', ' G G L L G L L L L L L G ')
AddSamavrtta('chidram', ' G G L L L ')
AddSamavrtta('parimalam', ' L L L L G G L L L L G L L G G ')
AddSamavrtta('virāṭ', ' G G G L L G L G L G ')
AddSamavrtta('vikuṇṭhakaṇṭhaḥ', ' G L G L G L G L G L G L G L G L G L G L G L G L G G ')
AddSamavrtta('vinandinī', ' L L G L L G L L G L L G L G ')
AddSamavrtta('rāmābaddham', ' G G G G L L L L G G L L G G L L L L G G L L G ')
AddSamavrtta('jaladharamālā', ' G G G G L L L L G G G G ')
AddSamavrtta('abhīkam', ' L G G L G G G ')
AddSamavrtta('dūrāvalokaḥ', ' G G G G L G G L L L L L L G G G L G G L G ')
AddSamavrtta('purohitā', ' L G L G L G G ')
AddSamavrtta('prothā', ' G G G L L L ')
AddSamavrtta('nakhapadā', ' L L L G L G G L ')
AddSamavrtta('pārāvārāntastham', ' G G G G G G G G G L L G G L L L L G G G L L G ')
AddSamavrtta('vaḍiśabhedinī', ' L L L G L L L G L G ')
AddSamavrtta('karmaṭhaḥ', ' G L L G L L G L L G L L G ')
AddSamavrtta('vigāhitageham', ' L L L L L L L L L L G G G G G L L L L G L L G G ')
AddSamavrtta('kamalaparam', ' L L L L G G L L L L G G G L L G ')
AddArdhasamavrtta('sācīkṛtavadanā', ' L L L L G G G L L G G ', ' G G L L L L G L L L L G ')
AddSamavrtta('vaṁśottaṁsā', ' G G L L G G L L G G G G G G ')
AddSamavrtta('karṇāṭakam', ' G G L G L L L G L G L L L G L G L L L L L L L L L G ')
AddSamavrtta('maru', ' L G L G L L L L ')
AddArdhasamavrtta('ardharutam', ' G L L L L L L G G L L L L ', ' G L L L L L L G L L G L L ')
AddSamavrtta('acalapaṅktiḥ', ' G L G L L L L L G G ')
AddSamavrtta('vṛndā', ' G G L G L G L ')
AddSamavrtta('lalitālabālam', ' L L G L G L L G G G G ')
AddSamavrtta('madhumallī', ' L L G G L L G L G ')
AddSamavrtta('pratīpavallī', ' L L G L L G G L L G L G L G G G ')
AddSamavrtta('nagamahitā', ' L L G G L L G L L L L G ')
AddSamavrtta('bhājanaśīlā', ' G G L L G G G L G G L G G ')
AddSamavrtta('prabhāvatī', ' G G L G L L L L G L G L G ')
AddVishamavrtta('ārdrā', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('viṣāṇāśritam', ' L G G L L L G L G G L L L G L G G L L L G L G G L G ')
AddSamavrtta('ardhakusumitā', ' G L L L L G L L L L L L G ')
AddSamavrtta('bhāsitasaraṇiḥ', ' G L L L L L L L L L L G ')
AddSamavrtta('ammethī', ' G G G G L G L ')
AddSamavrtta('citrapadā', ' G L L G L L G G ')
AddArdhasamavrtta('śālabhañjikā', ' L L G L L L G L G L G ', ' G L L G G L G L G L G ')
AddSamavrtta('abhrabhramaśīlā', ' G G L L G G L L G G L L G ')
AddSamavrtta('haraṇi', ' L L L ')
AddSamavrtta('prapātāvatāram', ' L G G L G G G L G L G ')
AddSamavrtta('lolatanu', ' L L G G L L L ')
AddSamavrtta('aṭṭāsinī', ' G G L G L L G L G L L G L ')
AddSamavrtta('darpamālā', ' L G G L G G G L G G L G G ')
AddSamavrtta('navasarā', ' G G G L L L G ')
AddSamavrtta('bhūriśikhā', ' L L G L L G G G G G G L L G ')
AddSamavrtta('dhavalakarī', ' L L L L L L G L L G G G ')
AddSamavrtta('atijani', ' G G G G L L L L ')
AddSamavrtta('śaralīḍhā', ' L L L L G L L G G ')
AddArdhasamavrtta('mārdaṅgī', ' L L G L L L L L G L L L G G ', ' G G G L L L L G L L L L L L L L G G ')
AddSamavrtta('proñchitā', ' L L G G L G L ')
AddSamavrtta('kāhī', ' L L G G G L L ')
AddSamavrtta('dvimilā', ' L L G L L G L L G L L G L L G L L G L L G L L G ')
AddArdhasamavrtta('aparaprīṇitā', ' L L L L L L L L G G G L G G L G ', ' L L L L L L G G L G G L G ')
AddSamavrtta('ḍhuṇḍhi', ' L L G G G L ')
AddArdhasamavrtta('pramāthinī', ' L L L L G L L G L G L G G ', ' L L G G L L G L G L G G ')
AddSamavrtta('taralanayanam', ' L L L L L L L L L L L L ')
AddSamavrtta('bhramarāvalikā', ' L L G L L G L L G L L G L L G ')
AddSamavrtta('mayūrī', ' L G G G L G L ')
AddSamavrtta('utpalamālikā', ' G L L G L G L L L G L L G L L G L G L G ')
AddSamavrtta('madhupāli', ' L L G L L G L L G L L G L L ')
AddSamavrtta('vipulapālikā', ' G L G L G L L L L G L G ')
AddSamavrtta('ardhakalā', ' L L G L L G L L G ')
AddSamavrtta('modakam', ' G L L G L L G L L G L L ')
AddSamavrtta('prasṛmaramarālikā', ' L L L L L G L G L G L G ')
AddSamavrtta('viralā', ' L L G L L L L G L G L G ')
AddSamavrtta('bālavikrīḍitam', ' G L L L L G L G L L L G L G G L G ')
AddArdhasamavrtta('anāsavavāsitā', ' L L G G L L G L G L G L L L G G ', ' L L L G L L L G L G L G L G G ')
AddSamavrtta('ṛju', ' L G L L ')
AddSamavrtta('karālī', ' G G L G G L G G ')
AddSamavrtta('meduradantam', ' G L L G L L G L L G L L G L L G L L G L L G L L ')
AddSamavrtta('kālambī', ' G G G L G L L ')
AddSamavrtta('gotragarīyaḥ', ' G L L G G L L L L G G L L G G L L L L G L L G ')
AddSamavrtta('puṭaḥ', ' L L L L L L G G G L G G ')
AddSamavrtta('balorjitā', ' L L L L G L G L G L G G ')
AddSamavrtta('doṣā', ' G G L L G L L ')
AddSamavrtta('anāsādi', ' G L G L G G L ')
AddSamavrtta('kośi', ' G L L L L L L ')
AddSamavrtta('vārddhi', ' L G L G L ')
AddSamavrtta('tuṅgā', ' L L L L L L G G ')
AddSamavrtta('kalpalatāpatākinī', ' G G G L L L L L L L L G L L G L G L G ')
AddSamavrtta('campakamālā', ' G L L G G G L L G G ')
AddSamavrtta('kurarīrutā', ' L L L L G L G L L L G L L G ')
AddArdhasamavrtta('śiśumukhī', ' L L L G L L L G L L G L G ', ' L L L G L L L L G L G L G ')
AddSamavrtta('atimohā', ' L L G G L L G G ')
AddSamavrtta('gaganodgatā', ' G L G L L L G L G L L G L G ')
AddSamavrtta('ākatanu', ' L G L G G L L L ')
AddSamavrtta('pravāhikā', ' L G L G G L G G L G G L G ')
AddSamavrtta('arajaskā', ' L G L L G G ')
AddSamavrtta('unnālam', ' G G L L L L L L G G ')
AddSamavrtta('bahulābhram', ' L L G G L L L L G G L L G G G ')
AddSamavrtta('vikatthanam', ' L G L L G L L L G L L G ')
AddArdhasamavrtta('karṇinī', ' G L G L L L G L L G G ', ' G L G L L L G L G L G ')
AddVishamavrtta('vaidhātrī', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('vaiśvadevī', ' G G G G G G L G G L G G ')
AddSamavrtta('śaṅkhadyuti', ' L L G G L L ')
AddArdhasamavrtta('pramodapariṇītā', ' L L L L L L G L G L G L G G ', ' L L L L G L L G L G L L L G G ')
AddSamavrtta('kuhī', ' L G L L L G ')
AddSamavrtta('niṣadham', ' G L L G L G L L G ')
AddSamavrtta('sopadhi', ' G L G G L L ')
AddArdhasamavrtta('saṁpātaśīlā', ' G G L G G G G L G G ', ' L L G L L L G G G L G G ')
AddSamavrtta('varīyaḥ', ' L G G L L ')
AddSamavrtta('kīralekhā', ' L L L G L G L L L G L G G ')
AddArdhasamavrtta('prabhāsitā', ' G G G L L G L G L G ', ' L L G L L G L G L G ')
AddSamavrtta('samit', ' L L L L G G L L L L G ')
AddSamavrtta('kīlālam', ' G L L G G G G G L L ')
AddSamavrtta('pravaralalitam', ' L G G G G G L L L L L G G L G G ')
AddSamavrtta('vīraṇamālā', ' G L L G G L L L L L L G ')
AddSamavrtta('anindagurvinduḥ', ' L L L L G G G G L G L G G G ')
AddSamavrtta('varivaśitā', ' L L G L L G L L L L L L G ')
AddSamavrtta('vinidrasindhuraḥ', ' G L G G L G G L G G L G L G L G L G L G L G L G L G ')
AddSamavrtta('lalitā', ' G G L G L L L G L G L G ')
AddSamavrtta('phulladāma', ' G G G G G L L L L L L G G L G G L G G ')
AddSamavrtta('aprītā', ' L L L G G G L L ')
AddSamavrtta('dhaureyam', ' G L L G L L L L G L L G L L L L L L L L G G G G ')
AddSamavrtta('mantrikā', ' G L G G G L ')
AddSamavrtta('kalpāhārī', ' L L L L L L L L L L L L G G G G ')
AddSamavrtta('bhujagahāriṇī', ' L L L G L G L L G L G ')
AddSamavrtta('śiprā', ' G G G G G G G ')
AddSamavrtta('hindīram', ' G G G G G L G ')
AddSamavrtta('śukavanitā', ' L L G L L G G L L G L L L L L L G ')
AddSamavrtta('māyāvinī', ' L L G G G L G ')
AddSamavrtta('mattakokilam', ' G L G L L G L G L L G L G L L G L G ')
AddSamavrtta('puṣpaśakaṭikā', ' G L L L L G G G L G G L G G ')
AddSamavrtta('kuberakaṭikā', ' L L G L L G L G L L L G G ')
AddSamavrtta('narāvaliḥ', ' G G L G L L L L L L L L G ')
AddSamavrtta('vaṁśapatrapatitam', ' G L L G L G L L L G L L L L L L G ')
AddSamavrtta('narī', ' L G G L G ')
AddSamavrtta('śarakāṇḍaprakāṇḍam', ' L L G G L G L L L G L G G L G G L G G L G ')
AddSamavrtta('nandathu', ' G L L L G G L ')
AddSamavrtta('karṇalatā', ' L L G G L L G L L L L G L L G ')
AddSamavrtta('kanakamañjarī', ' L L L G L G G L G L G ')
AddSamavrtta('ṛcā', ' L G L L G G L ')
AddSamavrtta('mattamayūraḥ', ' G G G G G L L G G L L G G ')
AddSamavrtta('guṇasārikā', ' L G L L G L L G L L G L G ')
AddSamavrtta('saurabhaśobhāsāraḥ', ' G L L G G G G G L L L L L L G L L L L G ')
AddSamavrtta('kaṭhinī', ' L L L L L G L G L G G L G ')
AddSamavrtta('ūhinī', ' G L G L L G L G G L G L L G L ')
AddVishamavrtta('māyā', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('vātormī', ' G G G G L L G G L G G ')
AddSamavrtta('nīranidhiḥ', ' L L L G G L L L L L ')
AddSamavrtta('madhu', ' L L ')
AddArdhasamavrtta('sundarī', ' L L G G L L G L G L G ', ' L L G L L G L G L G ')
AddSamavrtta('samānikā', ' G L G L G L G L ')
AddSamavrtta('gṛhiṇī', ' L L G G G G L ')
AddSamavrtta('vandāruḥ', ' G G G L L G G L L ')
AddSamavrtta('ardhāntarālāpi', ' G G L G G L G G L G G L G G L G G L ')
AddArdhasamavrtta('kamalākarā', ' G L L G L L G L L G G ', ' G L L L L L L G L L G G ')
AddSamavrtta('bhujaṅgī', ' L G G L G G L G G L G ')
AddSamavrtta('bhastrānistaraṇam', ' G G G L L G G L L L L L L G L G L G L L G G ')
AddSamavrtta('indravimānam', ' G L L G G L L L L G G G G L L L L L L L L G G ')
AddSamavrtta('drutapadam', ' L L L G L L L G L L G G ')
AddSamavrtta('mandākrāntā', ' G G G G L L L L L G G L G G L G G ')
AddSamavrtta('cakitā', ' G L L L L G G G G G G L L L L G ')
AddSamavrtta('suvanamālikā', ' G G L L L G L G L L L G ')
AddSamavrtta('vajrālī', ' G G L L G G G G G G G G G G G ')
AddArdhasamavrtta('kalanā', ' L L G L G L L L G L L G G ', ' L L G L G L L L G L G L G ')
AddSamavrtta('bhāsamānabimbam', ' G L G L G L G L L L L G L G L G L L L L G L G G ')
AddSamavrtta('ayanapatākā', ' G G G L L L G G G ')
AddSamavrtta('haripadam', ' L L L L L L L G ')
AddSamavrtta('candravartma', ' G L G L L L G L L L L G ')
AddSamavrtta('bhasalamadam', ' G L L L L G L G L G G L G ')
AddSamavrtta('mihirā', ' L L L L L G L G G L G G ')
AddSamavrtta('hīralambi', ' G L L G L L G L G L ')
AddSamavrtta('pṛthvī', ' L G L L L G L G L L L G L G G L G ')
AddSamavrtta('dolā', ' L L G G ')
AddSamavrtta('vidalā', ' L L L L L G G G L G L L G ')
AddSamavrtta('mukulitakalikāvalī', ' G L G L L L L L L G L G ')
AddArdhasamavrtta('atiprativinītā', ' L L G G L L G L G L L L G G ', ' L L L L G G L G L G L G G ')
AddSamavrtta('lalitapatākā', ' L L L L L G L G G L G G G G ')
AddSamavrtta('tilakā', ' L L G L L G ')
AddSamavrtta('cūḍāpīḍam', ' G G G G L L L L L L G G G G ')
AddSamavrtta('drutamukham', ' L L L L L L L L L L L L G G G G L G L G G G ')
AddSamavrtta('kulacāri', ' L G L G L L G L ')
AddSamavrtta('varhāturā', ' G G L G L L G G L G ')
AddSamavrtta('sākṣī', ' L L G L L G L G L G G G ')
AddSamavrtta('manoramā', ' L L L G L G L G L G ')
AddSamavrtta('rodhakam', ' L L L G L L G L L G G ')
AddSamavrtta('hāṭakaśāli', ' G G L L G L ')
AddSamavrtta('dantālikā', ' G G L G G G G L G G G G L G G L ')
AddSamavrtta('mañjubhāṣiṇī', ' L L G L G L L L G L G L G ')
AddSamavrtta('jāhamukhī', ' G L L G L L G L L G L L G G ')
AddSamavrtta('nemadhāri', ' L G L G L L G L G L ')
AddSamavrtta('madanajavanikā', ' L L L L G G L L L L L L G ')
AddSamavrtta('niravadhigatiḥ', ' L L L L L G G L L L G ')
AddSamavrtta('kṛtakatikā', ' L L L L L L L L L L L G ')
AddSamavrtta('ṭaṅkaṇam', ' G L G L L L G L G L L L G L G L L L G ')
AddSamavrtta('dhūmrālī', ' L G G L G G G G G G ')
AddSamavrtta('maṇḍalam', ' G L L L G ')
AddSamavrtta('sainikam', ' L G L G L G L G L G L ')
AddSamavrtta('madanamālikā', ' L L L G L G L L L G L G G L G ')
AddSamavrtta('vidhuravirahitā', ' L L G G G L L G G G L L L L L L G ')
AddSamavrtta('upadārikā', ' G L G L G L L L G L G ')
AddSamavrtta('badhirā', ' L L G G L L G L G L G G ')
AddArdhasamavrtta('hariluptā', ' L L G L L G L L G L G ', ' L L G G L L G L L G L G ')
AddArdhasamavrtta('viyadvāṇī', ' L L G G L L G L G L G G ', ' G G G L L G L G L G G G ')
AddArdhasamavrtta('aparavaktram', ' L L L L L L G L G L G ', ' L L L L G L L G L G L G ')
AddArdhasamavrtta('avahitrā', ' G L L G L L G L L G G ', ' L L G L L G L L G L L ')
AddSamavrtta('gaganagatikā', ' G L G L L G L G L L L L L G ')
AddSamavrtta('amṛtagatiḥ', ' L L L L G L L L L G ')
AddSamavrtta('tantrī', ' G G G L G G ')
AddSamavrtta('kalahetikā', ' L L G L G L L G L G L L L G ')
AddSamavrtta('valabhī', ' G L L G L L G L G L G G ')
AddArdhasamavrtta('ketumatī', ' L L G L G L L L G G ', ' G L L G L G L L L G G ')
AddArdhasamavrtta('kinnaṭakaḥ', ' G G L L G L L G L L G ', ' L L G L L G L L G L L G ')
AddSamavrtta('makaramukhī', ' L L L L L L L L L G ')
AddSamavrtta('mukhalā', ' L L L L G G L L G ')
AddSamavrtta('atiśāyinī', ' L L G L L G L G L G L L L G L G G ')
AddSamavrtta('karamālā', ' L L G G L L G G L L G G ')
AddSamavrtta('mahodhikā', ' L G L G L L G ')
AddSamavrtta('bhrūḥ', ' L G G G L ')
AddSamavrtta('upadhāyyā', ' G L L L L L L L G G ')
AddSamavrtta('balākā', ' L G G ')
AddSamavrtta('vilambalalitam', ' L G L L L G L G L L L G L G L L L G L G L L G ')
AddSamavrtta('virudarutam', ' G G G G L L L L G G L L G G L L G ')
AddSamavrtta('vāsantī', ' G G G G G L L L L G G G G G ')
AddSamavrtta('viraloddhatā', ' G G G L L G L G L L L G ')
AddSamavrtta('jatu', ' L L G L L ')
AddArdhasamavrtta('naṭakaḥ', ' L L G L L G L L G L L G ', ' G G L L G L L G L L G ')
AddSamavrtta('śalabhalolā', ' L G G L G G L G L L L G G ')
AddSamavrtta('ṣaṭpaderitam', ' L L L G L G L L L G L G L L L G L G ')
AddSamavrtta('alakālikā', ' G G L G L L G L G L L G L G ')
AddSamavrtta('rūpāmālī', ' G G G G G G G G G ')
AddArdhasamavrtta('vimāninī', ' G G G L L L L G L G L G ', ' L L G G L L G L G L G ')
AddSamavrtta('pathikāntā', ' G L L L L L L G L L G G ')
AddSamavrtta('śramitaśikhaṇḍī', ' G L L L L G G L L G G ')
AddSamavrtta('pramodatilakā', ' G G L G L L L G L L G L G ')
AddArdhasamavrtta('karīritā', ' L L G G L L L G L G L G ', ' L L G L L G L G L G ')
AddSamavrtta('śāradacandraḥ', ' G G L L G G L L G G L L G G ')
AddSamavrtta('svarṇābharaṇam', ' L L G L L G L L G L L G L L L L G G G L L G ')
AddSamavrtta('somaśruti', ' L G G G L L ')
AddSamavrtta('kroḍakrīḍam', ' G G G G L L L L L L L L G L G G L G ')
AddSamavrtta('naraśikhī', ' L L L G L L L G L L L G L L L G ')
AddSamavrtta('nīlagirikā', ' G L L L G L L L G L L G ')
AddSamavrtta('amitanagānikā', ' G L L L L G L G L L G L G ')
AddArdhasamavrtta('upacitrā', ' L L G L L G L L G L L ', ' G L L G L L G L L G G ')
AddSamavrtta('bhārākrāntā', ' G G G G L L L L L G L G L L G L G ')
AddSamavrtta('kupyam', ' G L L L L G L G L G ')
AddArdhasamavrtta('ahīnatālī', ' G G G L L L L G L G L G ', ' L L G G L L L L G L G L G L G G ')
AddSamavrtta('vasanaviśālā', ' L L L L L L L G G G G G ')
AddSamavrtta('kalahaṁsaḥ', ' L L G L G L L L G L L G G ')
AddSamavrtta('pṛṣadvatī', ' G G L G L G G L G L G L G ')
AddSamavrtta('nirvādhikā', ' G G L G L L G ')
AddSamavrtta('anavīrā', ' L L G G L L L L G ')
AddSamavrtta('vipulāyitam', ' G G G L L L L G L G L L L L L L G L G L G L G ')
AddSamavrtta('ativāsitā', ' L L G L G G G L G L L G ')
AddSamavrtta('kṛtayuḥ', ' L L L L L L L L ')
AddSamavrtta('arditapādam', ' G L G L L L L G L L G G ')
AddSamavrtta('veśi', ' G L L L L L L L ')
AddSamavrtta('rañjakam', ' G L L L L G L L G ')
AddSamavrtta('tāvuri', ' G G L L ')
AddSamavrtta('digīśaḥ', ' L L G L G L G G ')
AddSamavrtta('vāṇinī', ' L L L L G L G L L L G L G L G G ')
AddSamavrtta('kiṇapā', ' G L L L G G G ')
AddSamavrtta('viśakalitā', ' G G G G L L L L G G L L L L G ')
AddSamavrtta('sukarṇapūram', ' L L L G L G L G L G L G G ')
AddSamavrtta('ānanamūlam', ' G L L G G L L G G L L G G ')
AddSamavrtta('alakā', ' L L L L L L L L L L L L L L L L L L L L L L L L G ')
AddSamavrtta('kurarikā', ' L L L G L G G G ')
AddSamavrtta('aśokānokaham', ' G G G G L L L L L G L L L L L G L G G G L G G L G G ')
AddSamavrtta('yamanakam', ' L L G L L L G ')
AddSamavrtta('īdṛṣam', ' G L G L G L G L G L G L G L G L G L G L ')
AddVishamavrtta('ratākhyānakī', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('udarkaracitā', ' L L G L L G L G L L L G ')
AddSamavrtta('alolā', ' G G G L L G G G G G L L G G ')
AddSamavrtta('parilekhaḥ', ' L G L L G L L G L L G G ')
AddSamavrtta('javanaśālinī', ' L L G L L G L G G L G ')
AddSamavrtta('vasantahāsaḥ', ' G G G G L L L L G L G G ')
AddSamavrtta('karmadā', ' G L G L L G ')
AddSamavrtta('sīdhuḥ', ' L L G G L L G L G L G ')
AddSamavrtta('cayanam', ' L G G L L L L L ')
AddArdhasamavrtta('hariṇīplutā', ' L L L G L L G L L G L G ', ' L L G L L G L L G L G ')
AddSamavrtta('gallakam', ' L L L L L L L G G L G ')
AddSamavrtta('viṣṭambhaḥ', ' L L G L L G L L G G G ')
AddSamavrtta('prabhadrakam', ' L L L L G L G L L L G L G L G ')
AddSamavrtta('śambūkaḥ', ' L L G G G G G ')
AddSamavrtta('vāriśālā', ' L G L G G L G G ')
AddSamavrtta('anu', ' L L L L G G L ')
AddSamavrtta('arbhakamālā', ' G L L G G L L L L G G L L L L G G G L L G G ')
AddSamavrtta('śallakaplutam', ' L L G G L G L G ')
AddArdhasamavrtta('asurāḍhyā', ' G G G L L G L G L G G ', ' L L L L L L G L G L G G ')
AddSamavrtta('rucivarṇā', ' L G L L L G L G L L L G G ')
AddSamavrtta('antarvanitā', ' G G G L L G G G G G G ')
AddSamavrtta('kalamatallikā', ' L L L G L G L L L G L G L L L G L G G L G ')
AddSamavrtta('hali', ' L L L L L ')
AddSamavrtta('bhujaṅgasaṅgatā', ' L L G L G L G L G ')
AddSamavrtta('vāridhiyānam', ' G L L G G L L G L ')
AddSamavrtta('praharaṇakalikā', ' L L L L L L G L L L L L L G ')
AddArdhasamavrtta('vimukhī', ' L L L L L L G L L L L G G ', ' L L L L L L L L G L L G G ')
AddSamavrtta('haṭhinī', ' G G G L G L L G ')
AddSamavrtta('maulisrak', ' G G G L L G L ')
AddSamavrtta('kalādharaḥ', ' G L G G L G L G L G L G L G ')
AddSamavrtta('vaṁśalaḥ', ' G L L G G L L G L L G L L G L L G ')
AddSamavrtta('pāṁśu', ' L L L G L ')
AddSamavrtta('sandhyā', ' G G L L L L G G ')
AddSamavrtta('sāmapadā', ' G G G L L G L L L L G ')
AddSamavrtta('amaracamarī', ' L L L L L L L L L L L L L L L L L L L L L L G ')
AddSamavrtta('halamukhī', ' G L G L L L L L G ')
AddSamavrtta('pāli', ' L L G G L ')
AddSamavrtta('saṁśrayaśrīḥ', ' G G L G G L G G L G L ')
AddSamavrtta('lalitam', ' L L L L L L G G G G L G ')
AddSamavrtta('paṅkajadhāriṇī', ' G G G L L G L G L L L G G ')
AddSamavrtta('padmāvarttaḥ', ' G G G G G G G G G G ')
AddSamavrtta('paridhārā', ' L L G G L G G G ')
AddSamavrtta('pramāṇikā', ' L G L G L G L G ')
AddSamavrtta('ulapā', ' G L L L L L G ')
AddSamavrtta('pārṣatasaraṇam', ' G L L L L L L G G G G G L L L L L L L L L L G G ')
AddSamavrtta('upavali', ' L L L L L L ')
AddSamavrtta('ākekaram', ' G G L L L L L L G ')
AddSamavrtta('viṭ', ' G L L G L ')
AddSamavrtta('jananidhivelā', ' L L L L G G L L G G G G L L G ')
AddSamavrtta('candrāpīḍam', ' G G G G G G G G G G G G G G G G ')
AddSamavrtta('adritanayā', ' L L L L G L G L L L G L G L L L G L G L L L G ')
AddArdhasamavrtta('amarāvatī', ' L G L G L G L G L G L G G ', ' G L G L G L G L G L G L ')
AddSamavrtta('kalāpadīpakam', ' G L G L G L G L G L G L G L G L G L G ')
AddSamavrtta('vīravimānam', ' G L L G L L G L L G L L G L L G L L G G ')
AddArdhasamavrtta('viparītākhyānakī', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('kṣaram', ' L G L L L L L L ')
AddArdhasamavrtta('aruntudaḥ', ' L L G L L G L G L G ', ' L L L L G L L G L G L G ')
AddSamavrtta('śaśikarī', ' L L G L L L G G L ')
AddSamavrtta('culakam', ' L L L L L L L L L ')
AddSamavrtta('kṛkapādi', ' L L L G L G L L G L ')
AddSamavrtta('kṣupam', ' L G L L L ')
AddSamavrtta('sammadamālikā', ' L L L L L G L L G L G ')
AddArdhasamavrtta('padmāvatī', ' L L G L G L L L G L L G G ', ' G G L G L L L G L L G G ')
AddSamavrtta('sari', ' L L L L L G ')
AddSamavrtta('nīrohā', ' L L G G L G G G G G ')
AddSamavrtta('valivadanam', ' L L L L G G G G G G L L L L G G ')
AddVishamavrtta('kumārī', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('garudavāritā', ' L G L L L G L G L L G L G ')
AddArdhasamavrtta('drutamadhyā', ' G L L G L L G L L G G ', ' L L L L G L L G L L G G ')
AddSamavrtta('jīmūtadhvānam', ' G G G G G G G G G G G G G G G G G G G G G G G G G G ')
AddSamavrtta('kaladhautapadam', ' L L G L L G L L G L L G L L G G ')
AddSamavrtta('ciraruciḥ', ' L G G L L L G ')
AddSamavrtta('satketuḥ', ' G G G L L L L L L L G L G L G L G G ')
AddSamavrtta('aniloddhatamukhī', ' L L L G L G G L G L L L G ')
AddSamavrtta('sitastavakaḥ', ' G G L G L L L G G L G L L L G G L G L L L G ')
AddSamavrtta('ṛtam', ' L L L L L L L L G L ')
AddSamavrtta('agarim', ' L L L L L L L L L L L ')
AddSamavrtta('nayamālinī', ' L L L L G L G L L L G G ')
AddSamavrtta('mālyopastham', ' L L L L L L L L L L G G G G G G ')
AddArdhasamavrtta('asudhā', ' L L G G L L G L G L G ', ' G G G L L G L G L G ')
AddSamavrtta('kalaham', ' L L G G L L G G G ')
AddSamavrtta('priyā', ' L L G L G ')
AddSamavrtta('pikālikā', ' G L L L G L L G L G L G ')
AddSamavrtta('dvāravahā', ' G L G G G L L G G G ')
AddSamavrtta('vidyā', ' G G L L G L L G ')
AddSamavrtta('līḍhālarkaḥ', ' G G G G G L L L G L G G ')
AddSamavrtta('viśvavirāṭ', ' G G G L L G L G L G G ')
AddSamavrtta('māṇḍavakam', ' L L L G G L L G ')
AddSamavrtta('karmiṣṭhā', ' G L L L L G G G G ')
AddSamavrtta('suvihitā', ' L G G L L G L G L L L G ')
AddVishamavrtta('varddhamānam', ' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L L L L G L L L L L L L L G ', ' L L L L L L L L L L G L L G G ')
AddSamavrtta('prākārabandhaḥ', ' G G L G G L G G L G G ')
AddSamavrtta('śīrśavirahitā', ' G G L L G G G L L G L L L L G ')
AddSamavrtta('ūpikam', ' L G G G G L G ')
AddSamavrtta('kaṅkaṇakvāṇaḥ', ' G L G G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('ānatā', ' G G G L L L G L G G L G G ')
AddSamavrtta('titikṣā', ' G L L L L L L G G L L L L L L G G ')
AddVishamavrtta('manahāsā', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('kalali', ' L L L G G ')
AddSamavrtta('tumulakam', ' L L L L L L L L L L L L L L L L L L ')
AddSamavrtta('upacitaratikā', ' G L L L L L L G L L G L G ')
AddSamavrtta('vṛtumukhī', ' L L L G L L G G ')
AddSamavrtta('udaraśri', ' L L G L L G G G G ')
AddSamavrtta('sugandhiḥ', ' L L G L L L L G G ')
AddSamavrtta('taravārikā', ' L L L L L G L L G L G L L G L G ')
AddSamavrtta('mṛgī', ' G L G ')
AddArdhasamavrtta('anaṅgapadam', ' G L L G L L G L L G L L G ', ' L L G L L G L L G L L G G ')
AddSamavrtta('sāraṅgaḥ', ' G G L G G L G G L G G L ')
AddVishamavrtta('śaṅkhacūḍā', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('khelāḍhyam', ' G G G L L G G G G ')
AddSamavrtta('kṛtamaṇitā', ' G L L L L L L L L G ')
AddSamavrtta('harikāntā', ' L L G G L L G G L L G ')
AddSamavrtta('anilohā', ' L L G G L L G G L L G G L L G G ')
AddArdhasamavrtta('hariṇīplutā', ' L L G L L G L L G L G ', ' L L L G L L G L L G L G ')
AddSamavrtta('sārāvanadā', ' G G L L G L G G ')
AddSamavrtta('śarahatiḥ', ' L L L L L L L L L L L L L L L ')
AddSamavrtta('prabodhaphalitā', ' G L G L L L G L G L L L G ')
AddSamavrtta('vāsaki', ' L L L L G L L ')
AddSamavrtta('plavaṅgamaḥ', ' G L L G L L G G L G L L G L G ')
AddSamavrtta('narācaḥ', ' L G L G L G L G L G L G L G L G ')
AddSamavrtta('mālatī', ' L L L L G L L G L G L G ')
AddSamavrtta('kandaḥ', ' L G G L G G L G G L G G L ')
AddSamavrtta('puraṭi', ' L L L L G L G ')
AddSamavrtta('anṛtanarma', ' L L G G L L G L ')
AddSamavrtta('aśokalokaḥ', ' G G G G G G G G G G G G G G L G L G G G G ')
AddSamavrtta('mahimāvasāyi', ' L L G G L L G L G L ')
AddArdhasamavrtta('akusumacaram', ' G L L L L L L G L L G G ', ' G L L G L L G L L G G ')
AddSamavrtta('bhīmāvarttaḥ', ' G G G G L L L L L L L L L L G G ')
AddSamavrtta('karapallavodgatā', ' L G G L G G L L G L G L G ')
AddSamavrtta('pārāntacārī', ' L G G G G L G G ')
AddSamavrtta('cāru', ' G L ')
AddSamavrtta('karṇiśaraḥ', ' G L L G L L G L L G G L L G ')
AddSamavrtta('paripuṅkhitā', ' G L G L L G L G L G L G ')
AddSamavrtta('madhumatī', ' L L L L L L G ')
AddSamavrtta('citrā', ' G G G G G G G G G L G G L G G ')
AddSamavrtta('vipinatilakam', ' L L L L L G L L L G L G G L G ')
AddSamavrtta('jagatsamānikā', ' L L G L L G L G L G L G G ')
AddSamavrtta('induvaṁśā', ' G G L G G L L G L G L G ')
AddSamavrtta('kalpakāntā', ' G L G G G L G G L G G L G G ')
AddArdhasamavrtta('nirmadhuvāri', ' G G L G L L G L G L L G L ', ' L L G L G L L L G L G L G ')
AddSamavrtta('jarā', ' L G L L G L L G L G ')
AddSamavrtta('bhinnapadam', ' G L L G L L L G L G ')
AddSamavrtta('varṇabalākā', ' L L G L L G G L L G G ')
AddSamavrtta('sindhusauvīram', ' G L G G L G G L G G L G G L G G L G ')
AddArdhasamavrtta('paravaktram', ' L L L L G L L G L G L G ', ' L L L L L L G L G L G ')
AddSamavrtta('nāgāri', ' L L G L G G G L ')
AddArdhasamavrtta('śiśirā', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('saurabhavarddhinī', ' L L L L G G L L G L G ')
AddSamavrtta('maṅkuram', ' G G G L G L ')
AddArdhasamavrtta('ketuḥ', ' G L L G L G L L L G G ', ' L L G L G L L L G G ')
AddSamavrtta('prasṛmarakarā', ' L L L L L G L G G L G ')
AddSamavrtta('kaṭhodgatā', ' L L G L G L G ')
AddSamavrtta('ahari', ' L L L L L G L ')
AddSamavrtta('ujjhitakadanam', ' G L L L L L L G L L G L L G L L L L L L L L L L G G ')
AddSamavrtta('kuraṅgāvatāraḥ', ' L G G L G G L L G L L G ')
AddSamavrtta('niṣkalakaṇṭhī', ' G L L G G G L L G G G L L G G L L G G L L G ')
AddArdhasamavrtta('prativinītā', ' L L L L G G L G L G L G G ', ' L L G G L L G L G L L L G G ')
AddSamavrtta('krīḍacandram', ' L G G L G G L G G L G G L G G L G G ')
AddArdhasamavrtta('avācīkṛtavadanā', ' G G L L L L G L L L L G ', ' L L L L G G G L L G G ')
AddSamavrtta('arāli', ' L G L L G L L G ')
AddSamavrtta('kiṣku', ' G G L G G L G L ')
AddSamavrtta('kalavallivihaṅgaḥ', ' L G L G G L L G G L G G ')
AddSamavrtta('gopāvedī', ' L L L G G G G G ')
AddSamavrtta('kirmīram', ' G G G G L G G ')
AddSamavrtta('viśalyam', ' L G G L G G L G G ')
AddSamavrtta('śambaram', ' L L L G L L G L L G L G L L L G L L G L L G L G ')
AddSamavrtta('varaśaśi', ' G L G L L L L ')
AddSamavrtta('kalilā', ' L L G L L G L G ')
AddSamavrtta('avandhyopacāraḥ', ' L G G L G G L G G L G G L G G L G G L G ')
AddSamavrtta('kākalīkalakokilaḥ', ' G L G L L G L G L L G L G L L G L G L L G L G L L G ')
AddSamavrtta('paṅkāvaliḥ', ' G L L L L L L G G L L L L ')
AddArdhasamavrtta('vaiyālī', ' L L L L L L G L G L G ', ' G G G L L G L G L G ')
AddSamavrtta('ibhabhrāntā', ' G G G L G G G ')
AddSamavrtta('sragviṇī', ' G L G G L G G L G G L G ')
AddSamavrtta('drutavilambitam', ' L L L G L L G L L G L G ')
AddSamavrtta('mithunamālī', ' L L L L L L G G G G G G ')
AddSamavrtta('upakārikā', ' L L G L G L L G L G L L G L ')
AddSamavrtta('kusumitalatāvellitā', ' G G G G G L L L L L G G L G G L G G ')
AddSamavrtta('upasarasī', ' L L G L L L L G L L L L G ')
AddSamavrtta('vidyullekhā', ' G G G G G G ')
AddSamavrtta('cakram', ' G L L L L L L L L L L L L G ')
AddSamavrtta('ahiṁsā', ' G L G L G G G ')
AddSamavrtta('arkaśeṣā', ' G L G L G L G L G L G L G G ')
AddSamavrtta('narhi', ' L G G L G G L ')
AddSamavrtta('śaśivadanā', ' L L L L G G ')
AddSamavrtta('cārucāraṇam', ' G L G L L L L L G L ')
AddSamavrtta('pratardi', ' L G L G L G L ')
AddSamavrtta('kheṭakam', ' G L L L G L G G L G ')
AddSamavrtta('godhi', ' L L G L L G L ')
AddSamavrtta('mānākrāntā', ' G G G G G G G G G G G G G G G G G ')
AddArdhasamavrtta('vāsavavanditā', ' G G G L L G L G L G ', ' G G L L G L G L G ')
AddSamavrtta('vaṁśastham', ' L G L G G L L G L G L G ')
AddSamavrtta('bhujagaśiśubhṛtā', ' L L L L L L G G G ')
AddSamavrtta('panthā', ' L G G G G G ')
AddSamavrtta('amarandi', ' G G L G L L G L ')
AddSamavrtta('parīvāhaḥ', ' L L L G G L G G L G G L G G ')
AddSamavrtta('mālāvalayam', ' G G G G L L L L G G L L L L G G ')
AddSamavrtta('aviralaratikā', ' G L L L L L L G L G L G ')
AddSamavrtta('vīrā', ' G G G G L L L L G ')
AddSamavrtta('kaḍāram', ' L G G L L L L G G G G ')
AddSamavrtta('troṭakam', ' L L L L G L G L G G L L G L L G ')
AddSamavrtta('adhikārī', ' L L G G L L G ')
AddSamavrtta('ayamānam', ' L L G L L G L L G L L G L L G L L G L L G G ')
AddSamavrtta('satī', ' L L L G ')
AddSamavrtta('atulapulakam', ' L L L L L L L L L L L L L L L L L L L L L L L G ')
AddSamavrtta('mattākrīḍam', ' G G G G G G G G L L L L L L L L L L L L L L G ')
AddSamavrtta('sāravarohā', ' G L L G G L L L L G G L L L L G ')
AddSamavrtta('kaucamāraḥ', ' L L G G G L G G ')
AddArdhasamavrtta('samudrakāntā', ' G G L L G L G L G G ', ' G G G L L G L G L G G ')
AddSamavrtta('bhīmābhogaḥ', ' G G G G G L G G L G G G G G G G L G G L G G ')
AddSamavrtta('tanumadhyā', ' G G L L G G ')
AddSamavrtta('kalasvanavaṁśaḥ', ' G L L G L L G G L L G ')
AddVishamavrtta('varāsikā', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('vidhunidhuvanam', ' G G G L L L L L L G G L L L L G G G G ')
AddSamavrtta('kūlam', ' G G L L L G G G G G ')
AddSamavrtta('madanamālā', ' L L L G L G L L L G G ')
AddSamavrtta('bhūridhāmā', ' L L G G L G G ')
AddSamavrtta('sāmikā', ' G L G G L G L ')
AddSamavrtta('śrutakīrttiḥ', ' L L L L G G G L L G G ')
AddSamavrtta('sūriṇī', ' G L G G G ')
AddSamavrtta('kāmalā', ' L L L L L L G G G L G G L G ')
AddSamavrtta('mitasakthi', ' L L L L L G L L G L G L L G L ')
AddArdhasamavrtta('pātaśīlā', ' L L G L L L G G G L G G ', ' G G L G G G G L G G ')
AddArdhasamavrtta('vargavatī', ' G L L G L L G L L G G ', ' L L G L L G L L G G ')
AddSamavrtta('lakṣaṇalīlā', ' G L L G G L G G G G G ')
AddSamavrtta('karañji', ' L G L L L L G L ')
AddSamavrtta('viśvaviśvāsaḥ', ' G G G L G G L G G L G G G L G G G G G G L G G L G G ')
AddSamavrtta('bhujaṅgaḥ', ' L G G L G G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('nandaḥ', ' G L G G ')
AddSamavrtta('lalanā', ' G L L G G G L L G L L G ')
AddSamavrtta('bahulayā', ' G L G L L L G ')
AddSamavrtta('dhamanikā', ' L L G L G L L L L G ')
AddSamavrtta('bhārāvatāraḥ', ' L L L G G L L G L L L L L L L G G L G G ')
AddSamavrtta('vārayātrikam', ' G L L G L G G L G L G ')
AddSamavrtta('paragatiḥ', ' G L G L L L L L G L L L G ')
AddSamavrtta('vidhāritā', ' L G L L G L L G L G L G ')
AddSamavrtta('sudhādharā', ' G L G L G L G G L G L G L G ')
AddSamavrtta('dārikā', ' L L G L G L L L G L G ')
AddSamavrtta('asitadhārā', ' L L G L L L L L G G ')
AddArdhasamavrtta('sundarī', ' L L G L L G L G L G ', ' L L G G L L G L G L G ')
AddSamavrtta('bhāṣā', ' L G G G L G L L ')
AddSamavrtta('saṅkalpāsāraḥ', ' G G G G G G G G G G G G G G ')
AddSamavrtta('vindhyārūḍham', ' G G G G L G G G G G G L G G ')
AddSamavrtta('holā', ' L L L G G G G ')
AddArdhasamavrtta('śiśiraśikhā', ' L L L L L L G L G L G ', ' L L L L G L L G L G L G ')
AddSamavrtta('śākhoṭaki', ' L L L G G G L L ')
AddSamavrtta('bhasalavinoditā', ' L G L G L L L L L G L G ')
AddSamavrtta('niskā', ' G G G L L G ')
AddSamavrtta('abhīrukā', ' L G L G L L L L L L L L G ')
AddSamavrtta('apayodhā', ' L L G G L G G G G G G ')
AddArdhasamavrtta('prabhāsitā', ' L L G L L G L G L G ', ' G G G L L G L G L G ')
AddSamavrtta('sarāvikā', ' L G L G L G L G L G ')
AddSamavrtta('saraghā', ' L L G G G L L G ')
AddSamavrtta('kuhū', ' L G L L G L L G L ')
AddSamavrtta('viṣamavyālī', ' L L L L L G G G G G G G ')
AddVishamavrtta('indumā', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('sragdharā', ' G G G G L G G L L L L L L G G L G G L G G ')
AddSamavrtta('candrahāsakarā', ' G L G L L G L G L L G L G ')
AddSamavrtta('indhā', ' G G L G L L ')
AddArdhasamavrtta('lāsyalīlālayaḥ', ' G G L L G G G L G G L G G ', ' G L L L L G G G L G G L G G ')
AddSamavrtta('adhīrā', ' G L L G G G G ')
AddSamavrtta('jaloddhatagatiḥ', ' L G L L L G L G L L L G ')
AddSamavrtta('dhīradhvānam', ' G G G G G G G G G L L G G G ')
AddSamavrtta('mālinī', ' L L L L L L G G G L G G L G G ')
AddArdhasamavrtta('arbhakapaṅktiḥ', ' L L G G L L G L G L G G ', ' G L L G L L G L G L G G ')
AddArdhasamavrtta('anūpakam', ' L L L L G L L G L G L G ', ' L L G L L G L G L G ')
AddSamavrtta('kusumavicitrā', ' L L L L G G L L L L G G ')
AddSamavrtta('kiśalayam', ' L L L G G G L ')
AddSamavrtta('kumudinīvikāśaḥ', ' L G L G G L L L G L G G ')
AddSamavrtta('svidā', ' L G L L L L G ')
AddSamavrtta('vāsakalīlā', ' G L L G G G L L G G G L L G G G L L G G G G ')
AddSamavrtta('uditam', ' L L G L L G L L G G ')
AddSamavrtta('sthālī', ' G G L G L G ')
AddSamavrtta('vāsaramaṇikā', ' G L L L L G L L G G L L ')
AddSamavrtta('bhūrivasu', ' L G G G L L L ')
AddSamavrtta('madanalalitā', ' G G G G L L L L L G G G L L L G ')
AddSamavrtta('asambādhā', ' G G G G G L L L L L L G G G ')
AddSamavrtta('madalekhā', ' G G G L L G G ')
AddSamavrtta('vaṁśalonnatā', ' G L G L G L G L G G G G G G G L G L G L G G G G ')
AddSamavrtta('yugadhāri', ' L L G L G G G G ')
AddSamavrtta('śalkaśakalam', ' G L L L G L L G L L G ')
AddSamavrtta('hāsikā', ' G G G L G ')
AddSamavrtta('mantharāyanam', ' L L L G L G L L L L L L G L L G L L G L L G G ')
AddSamavrtta('nārācikā', ' G G L G L G L G ')
AddSamavrtta('cakoraḥ', ' G L L G L L G L L G L L G L L G L L G L L G L ')
AddSamavrtta('masṛṇam', ' L L L L L L G G L ')
AddSamavrtta('sindhuk', ' G G L L L L L L ')
AddSamavrtta('elā', ' L L G L G L L L L L L L L G G ')
AddSamavrtta('prapātalikā', ' G L L L L G L G L G L L G ')
AddSamavrtta('rasadhārā', ' L L L L G G L L L L G G G ')
AddArdhasamavrtta('ulapohā', ' G L L G L L G L G L G G ', ' L L G G L L G L G L G G ')
AddSamavrtta('nirvindhyā', ' L G L L L G G G G ')
AddArdhasamavrtta('puṣpitāgrā', ' L L L L L L G L G L G G ', ' L L L L G L L G L G L G G ')
AddSamavrtta('upohā', ' L G G L G L L ')
AddSamavrtta('ari', ' G L L L L L L G ')
AddSamavrtta('pākali', ' L L L G L G L L ')
AddSamavrtta('marmasphuram', ' G G L G L L L G L G G L G ')
AddArdhasamavrtta('sarasīkam', ' G G L G L L L G L L G G ', ' L L G G L L L G L L G G ')
AddSamavrtta('ādhidaivī', ' L G G G G G L G G L G G ')
AddSamavrtta('vīranīrājanā', ' L G G L G G L G G L G G G L G G L G G L G G ')
AddSamavrtta('adhīrakarīram', ' G G G L L L L L L G L L L L G L L L L G L L G G ')
AddSamavrtta('haṁsamālā', ' G L G G L G G ')
AddSamavrtta('sṛtamadhu', ' L L G G L L L L ')
AddSamavrtta('savyālī', ' G G G G G G G G G G G G G ')
AddSamavrtta('mārābhisaraṇam', ' G G L L L L G G G G L L L L G L G G G ')
AddSamavrtta('nirmuktamālā', ' G G G G L G G L L L L L L G ')
AddSamavrtta('akṣarāvalī', ' G L G L L G L G L G ')
AddSamavrtta('pañcaśākhī', ' L L L L L G L G L G G ')
AddSamavrtta('kumudamālā', ' L L L G G L L L G G L L L G G L L L G G L L L G G ')
AddSamavrtta('rasabhūma', ' L L G L G L L L G L ')
AddArdhasamavrtta('upodgatā', ' L L G G L L G L G L G G ', ' L L G L L G L G L G G ')
AddSamavrtta('avoḍhā', ' G G G G L G ')
AddVishamavrtta('mālā', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('somarājī', ' L G G L G G ')
AddSamavrtta('gūrṇikā', ' G L G G G L L ')
AddSamavrtta('paṅkavatī', ' G L L L L L L G L L G L L ')
AddSamavrtta('manmathaḥ', ' L L G L L G G L L G L L G G ')
AddSamavrtta('saudāmanadāma', ' L L G L L G L L G L L G L L L L G L L G G L L G L ')
AddSamavrtta('madhumārakam', ' L L G L G L ')
AddSamavrtta('caṇḍī', ' L L L L L L L L G L L G G ')
AddSamavrtta('kharviṇī', ' G L G G G G L ')
AddSamavrtta('bhujaṅgoddhatam', ' G G L G L L G L G G L G L L G G L G L L L G ')
AddSamavrtta('ārādhinī', ' G G L G G G G G G G G ')
AddSamavrtta('kanakamālikā', ' G L G L L L G L G L L L G L G L L L G L G ')
AddSamavrtta('ruciram', ' G L L L L G G ')
AddSamavrtta('arti', ' L G G L L L ')
AddSamavrtta('nameruḥ', ' G G L L G L G L G G ')
AddSamavrtta('nīlaśārdūlam', ' L L L L L L G G G L G G L G G L G G ')
AddSamavrtta('kalāpāntaritā', ' L G G L L G L G G G ')
AddArdhasamavrtta('aupagavam', ' L L L G L G G L G L G ', ' G L L G L G G L G L G ')
AddSamavrtta('virataprabhā', ' G L L G L L L L L G L G ')
AddSamavrtta('vīravaṭu', ' L L L G L L L ')
AddSamavrtta('kūlacāriṇī', ' G L G L G L G G G G G ')
AddSamavrtta('mattagajendraḥ', ' G L L G L L G L L G L L G L L G L L G L L G G ')
AddSamavrtta('vidyunmālā', ' G G G G G G G G ')
AddSamavrtta('pravahlikā', ' G L L L G L G L G ')
AddSamavrtta('śraddharā', ' G L G L G L L G ')
AddSamavrtta('sphoṭakṛīḍam', ' L L L L G G G G G G G G G G G ')
AddSamavrtta('mañjumālatī', ' G L G L G L L L G L G L G ')
AddSamavrtta('komalakalpakalikā', ' L L G L G G L L G L L L G ')
AddSamavrtta('lalāmalalitādharā', ' L G L G L G L G L G L G ')
AddSamavrtta('amandapādaḥ', ' G L L L L G L G L G G ')
AddSamavrtta('udayanamukhī', ' L L L L L G L L L L L G ')
AddArdhasamavrtta('viśvapramā', ' G G L G G L G G L G ', ' L G L G G L G G L G ')
AddSamavrtta('madanakam', ' L L L L L L L L G ')
AddSamavrtta('upagataśikhā', ' L L L L L G L G L L G L G ')
AddSamavrtta('kuṭhārikā', ' L G L G G L G ')
AddArdhasamavrtta('avarodhavanitā', ' L L L G L L G L L G L G L G ', ' L L G L L G L G L G L L L G G ')
AddSamavrtta('viśvamukhī', ' G L L G L L G L L G ')
AddSamavrtta('upasthitā', ' G G L L G L L G L G G ')
AddSamavrtta('śunakam', ' G L L G L G ')
AddSamavrtta('parabhānu', ' L G G L L G L ')
AddSamavrtta('vihāvā', ' L G G L G G L G ')
AddSamavrtta('virāmavāṭikā', ' L L L L G L G L G L L G L L L L G L G L G L L L L G ')
AddSamavrtta('upasaṁkulā', ' L L G L G L G G L G ')
AddSamavrtta('kanakitā', ' G L L G L L L L L L L L G ')
AddArdhasamavrtta('upasarasīkam', ' L L G G L L L G L L G G ', ' G G L G L L L G L L G G ')
AddSamavrtta('jāsari', ' G L L L G L L ')
AddSamavrtta('nūtanam', ' G L G L L L G L L G L L G L G ')
AddArdhasamavrtta('upodgatā', ' L L G L L G L G L G G ', ' L L G G L L G L G L G G ')
AddArdhasamavrtta('bhadrā', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('strī', ' G G ')
AddSamavrtta('pathyā', ' L L G L G L L L G L G G L G ')
AddSamavrtta('sūrasūcakaḥ', ' G G G L L G L G L L L G L L G L L G L G G L G G L G ')
AddSamavrtta('apavāhaḥ', ' G G G L L L L L L L L L L L L L L L L L L L L G G G ')
AddVishamavrtta('saurabheyī', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('sāvaṭu', ' L G L G L L ')
AddSamavrtta('kāntāram', ' L G G G G G L L L L L G G L G G L ')
AddSamavrtta('prapañcacāmaram', ' L L L L L L G L G L G L G L G L G L G ')
AddSamavrtta('tomaram', ' L L G L G L L G L ')
AddSamavrtta('kalādhāmam', ' G L L G L L L G L G G G G ')
AddSamavrtta('kṛtamālam', ' G G L L G L L G G G L L G G ')
AddSamavrtta('dharā', ' G G L G ')
AddSamavrtta('upalinī', ' L L L G L G L G ')
AddSamavrtta('caturīhā', ' L G L G L L G G ')
AddSamavrtta('saramāsaraṇiḥ', ' L L G L L G G G L G G L G G ')
AddSamavrtta('chāyā', ' L G G G G G L L L L L G G G L G G L G ')
AddSamavrtta('rasikarasālā', ' L L L L L L L L G L L G G L L G G L L L L L L G G ')
AddSamavrtta('jvalitā', ' L L G L L L L L L L L G ')
AddSamavrtta('kroḍāntikam', ' G G L G L L L ')
AddSamavrtta('virohi', ' L G L L L G L ')
AddSamavrtta('parimitavijayā', ' L L L L L L G L G L G G ')
AddArdhasamavrtta('avarodhavanitā', ' L L G L L G L G L G L L L G G ', ' L L L G L L G L L G L G L G ')
AddSamavrtta('vṛntam', ' L L G G G G L L ')
AddSamavrtta('hīrāṅgī', ' G G G L L L L G G G ')
AddSamavrtta('vipannakadanam', ' L L L G L G L L L G G G G ')
AddSamavrtta('sāndrapadam', ' G L L G G L L L L G L ')
AddSamavrtta('vanavāsinī', ' L L G L L G L G L G L L G L G L L L L L G L ')
AddSamavrtta('pikālī', ' G L G L G G ')
AddSamavrtta('vāmavadanā', ' G L L L G L G G L G G L G ')
AddSamavrtta('vikasitapadmāvalī', ' L L L L G G L G G G G ')
AddSamavrtta('vinatākṣī', ' L L G G L L L L L L L L G ')
AddArdhasamavrtta('yuddhavirāṭ', ' G G G L L G L G L G G ', ' G G L L G L G L G G ')
AddSamavrtta('dṛtiḥ', ' L L L L L G G ')
AddArdhasamavrtta('kiṁśukāvalī', ' G G G L L L L G L G L G G ', ' G G L L G L G L G G ')
AddSamavrtta('sairavī', ' G L G G G G G ')
AddSamavrtta('saṁlakṣyalīlā', ' L L L G L G L L L G L G L L L G G L G G ')
AddSamavrtta('kūrcalalitam', ' G L G G L G G L G G L L L G ')
AddSamavrtta('anṛju', ' G L L L ')
AddSamavrtta('madirā', ' G L L G L L G L L G L L G L L G L L G L L G ')
AddSamavrtta('śikhilikhitā', ' G G G L L L L G ')
AddSamavrtta('saralāṅghri', ' G G L L L G L ')
AddSamavrtta('līlālekhaḥ', ' G G G G G G G G G G G G G G G ')
AddSamavrtta('śakuntakuntalaḥ', ' G G G G L G G L G L L L L L L G L G L G L G L G L G ')
AddSamavrtta('krīḍā', ' L G G G ')
AddSamavrtta('vātuli', ' L G G L G G L L ')
AddSamavrtta('kumāralīlā', ' G G G L L L L L L G L G L G G ')
AddSamavrtta('vāsavilāsavatī', ' G L L G L L G L L G G G G ')
AddSamavrtta('rūpāvaliḥ', ' G G L L L L L L L L L G ')
AddSamavrtta('kṣamāpāli', ' L G L G G L ')
AddSamavrtta('prajñāmūlam', ' G G G G L L L L L L G G G ')
AddArdhasamavrtta('surahitā', ' L L L L L L L L G L L G G ', ' G G L L L L L L L L L L G ')
AddSamavrtta('gahanā', ' G L L L L L G L L G ')
AddSamavrtta('bhekālokaḥ', ' G L L G G G G G G G G L L L L L L G G G ')
AddSamavrtta('vellitavelam', ' G L L G L L G L L G G G L L G L L L L L L L L G ')
AddSamavrtta('ambudāvalī', ' L L G L G G L L G L G L G ')
AddArdhasamavrtta('luptā', ' L L G G L L G L L G L G ', ' L L G L L G L L G L G ')
AddSamavrtta('vilambanīyā', ' L L L G L L L L G L G L G G ')
AddSamavrtta('kuśalakalāvatikā', ' G G G L L L L G L L G ')
AddSamavrtta('siṁhalekhā', ' G L G L G L G G ')
AddSamavrtta('kelicaram', ' L L L L G G L L L L L ')
AddSamavrtta('mṛgendramukham', ' L L L L G L L G L G L G G ')
AddSamavrtta('vīraviśrāmaḥ', ' L L L L L L G L G L L L G L G G G ')
AddSamavrtta('haṁsarutam', ' G G G L L L G G ')
AddSamavrtta('madāvadātā', ' L L G G L L G L G L G L G G ')
AddSamavrtta('sampākaḥ', ' G G G G G L L ')
AddSamavrtta('vīravikrāntaḥ', ' G G G L L L L G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('lakṣmī', ' G L G G L G G L ')
AddSamavrtta('nandanam', ' L L L L G L G L L L G L G L G G L G ')
AddSamavrtta('kuhakakuharam', ' L L L L L L G G G L G G L L L L L L G G G L G G L G ')
AddSamavrtta('vāravatī', ' L L G G L L G L L G ')
AddSamavrtta('ārbhavam', ' G L G L G L ')
AddSamavrtta('līlālolaḥ', ' G G G G L L L L G G G G G ')
AddSamavrtta('vaśamūlam', ' L L G G L L L L G L G L G G ')
AddSamavrtta('vayasyaḥ', ' L G G G L G G ')
AddSamavrtta('kharpari', ' L G L G G L L ')
AddSamavrtta('sambodhā', ' L G L G G L L L L L L G G G ')
AddSamavrtta('tāmarasam', ' L L L L G L L G L L G G ')
AddSamavrtta('rucirā', ' L G L G L L L L G L G L G ')
AddSamavrtta('pañjari', ' G L L G G G L L ')
AddSamavrtta('vilulitamañjarī', ' L L L L G L G G G G G ')
AddSamavrtta('arthaśikhā', ' G L L L L L L G L L G ')
AddSamavrtta('lodhraśikhā', ' G G G L L G L L G L L G G ')
AddSamavrtta('kiñjalki', ' G G L G L ')
AddSamavrtta('pataṅgapādaḥ', ' L G L G G L G G L G G L G G L G G L ')
AddArdhasamavrtta('jāriṇī', ' L L L G G L G G L G ', ' G L G G L G L L L G G L G ')
AddSamavrtta('viśambhari', ' L L L L L L L G G L L L L L ')
AddSamavrtta('akhaniḥ', ' L L L L G L L G ')
AddSamavrtta('jālapādaḥ', ' G G L G G G G L G G G ')
AddSamavrtta('kāṇḍamukhī', ' L G L G L L G L L G ')
AddSamavrtta('indraphalā', ' G L L G G G G G ')
AddArdhasamavrtta('kalanāvatī', ' L L G L G L L L G L G L G ', ' L L G L G L L L G L L G G ')
AddSamavrtta('kañjā', ' L G L G G G ')
AddSamavrtta('vṛddhavāmā', ' G G L G G L L G L G G L G ')
AddSamavrtta('bhārṅgī', ' L G L L L G G G ')
AddSamavrtta('kuradi', ' L G L L L L L ')
AddSamavrtta('īḍā', ' G G L L L L L G ')
AddSamavrtta('śroṇī', ' L G L G G G L ')
AddSamavrtta('paṭupaṭṭikā', ' L L G L G L L G L G G ')
AddSamavrtta('maśagā', ' L G G L L G ')
AddSamavrtta('vedhāḥ', ' G G L L G G G ')
AddSamavrtta('meghālokaḥ', ' L G G G G G G G G ')
AddSamavrtta('anucāyitā', ' L L L L L G L G L G ')
AddSamavrtta('pratisīrā', ' G G G G L L G G ')
AddSamavrtta('sutalam', ' L L G G L G L L G G L G ')
AddSamavrtta('harṣiṇī', ' G L G G L L L ')
AddArdhasamavrtta('vaisārī', ' G G L L G L G L G ', ' G G G L L G L G L G ')
AddArdhasamavrtta('apramāthinī', ' L L G G L L G L G L G G ', ' L L L L G L L G L G L G G ')
AddSamavrtta('puṭamardi', ' L L L L G L ')
AddSamavrtta('samayaprahitā', ' L L G L L G L G G L G G ')
AddSamavrtta('viśālāntikam', ' G G L G G L G G L G ')
AddSamavrtta('śṛkhalavalayitam', ' G L L L L L L L L G L L G G G L L L L L L L G L L G ')
AddSamavrtta('parimalalalitam', ' L L L L L L G G L G G ')
AddSamavrtta('mandari', ' G L L ')
AddSamavrtta('kamalaśikhā', ' L L L L G G G G G G L L L L G L L G L L G ')
AddSamavrtta('sthūlā', ' G G L L L G G ')
AddSamavrtta('ahilā', ' G G L L L G L G L G ')
AddSamavrtta('prabhā', ' L L L L L L G L G G L G ')
AddSamavrtta('upasthitam', ' L G L L L G G G L G G ')
AddSamavrtta('śarabhūriṇī', ' G L G L L G L G L L G L G L L G L G L L G L G G G ')
AddSamavrtta('vaisāruḥ', ' G G L L L G G G G ')
AddSamavrtta('pratari', ' G L G L L L ')
AddSamavrtta('vārttāhārī', ' L L L L G L L G G G G ')
AddSamavrtta('nābhasam', ' L G L L G L L L G L G ')
AddSamavrtta('vīrāntā', ' L G L L L G G G G G ')
AddSamavrtta('kumbhakam', ' L L L L L L G L G G L G G L G G L G G L G G L G G L ')
AddSamavrtta('nimagnakīlā', ' L G L G G L L G L G G L ')
AddSamavrtta('vāri', ' L G G L ')
AddSamavrtta('saubhagakalā', ' G L L L G L L L G L G ')
AddArdhasamavrtta('haṁsī', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('śeṣāpīḍam', ' G G G G L L L L G L L ')
AddSamavrtta('viplutaśikhā', ' G L L L G L G L G G L G ')
AddArdhasamavrtta('sudhā', ' G G G L L G L G L G ', ' L L G G L L G L G L G ')
AddSamavrtta('ābhāsamānam', ' L G G L G G L G G L G G G G L G G L G G L G G L G G ')
AddSamavrtta('mallapallīprakāśam', ' L G G L G G L G G L G G L G G L G G L G G L G G L ')
AddArdhasamavrtta('hīnatālī', ' L L G G L L L L G L G L G L G G ', ' G G G L L L L G L G L G ')
AddArdhasamavrtta('karadhā', ' G G G L L G L G L G ', ' L L L L L L G L G L G ')
AddSamavrtta('vipākavatī', ' L L L G L L L G L L G L L G ')
AddSamavrtta('varkaritā', ' G G G G L L G ')
AddSamavrtta('gītikā', ' L L G L G L L G L G L L G L G L L G L G ')
AddSamavrtta('visasi', ' L L G L L L ')
AddArdhasamavrtta('baddhā', ' G G G G L L L L L L G ', ' L L G L L G L L L L L L G ')
AddSamavrtta('āśāpādaḥ', ' G G G G L L L L G L G ')
AddSamavrtta('suvadanā', ' G G G G L G G L L L L L L G G G L L L G ')
AddSamavrtta('kuśakam', ' G L G L L L L L ')
AddSamavrtta('ujjvalā', ' L L L L L L G L L G L G ')
AddArdhasamavrtta('kāmākṣī', ' L L G L L G L L L L L L G ', ' G G G G L L L L L L G ')
AddSamavrtta('acalanayanam', ' L L L L L L L L L L L L L L L L L ')
AddSamavrtta('pravādapadā', ' L L G L G L G L L G ')
AddSamavrtta('bhramaravilasitā', ' G G G G L L L L L L G ')
AddArdhasamavrtta('ākhyānakī', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('manthānakam', ' G G L G G L ')
AddSamavrtta('bhujalatā', ' L L L L L G G G L L G ')
AddSamavrtta('mayūkhasaraṇiḥ', ' G L L L L G L G L L L G G ')
AddSamavrtta('unnarma', ' G L L G L L L L G L L G G L ')
AddSamavrtta('kālavarma', ' L L L G L L L G L G L ')
AddSamavrtta('phaladharam', ' L L L L L L G L L G ')
AddSamavrtta('suri', ' L L L L G G G ')
AddSamavrtta('svāgatā', ' G L G L L L G L L G G ')
AddSamavrtta('bhāsitabharaṇam', ' G L L L L G G G G G G G ')
AddSamavrtta('bhasalaśalākā', ' G G G G L L L L G G G G L L L L G G G G L L L L G G ')
AddSamavrtta('krūrāśanam', ' G G L L L L G G L L L L L L G G G ')
AddArdhasamavrtta('pāṭalikā', ' L L L L G G L L L L G G ', ' G L L G L L G L L G G ')
AddSamavrtta('vaśaṁvadaḥ', ' L L G L L G L L G L L G L L G L L G L L G L L G L L ')
AddArdhasamavrtta('bhadravirāṭ', ' G G L L G L G L G G ', ' G G G L L G L G L G G ')
AddSamavrtta('nimnāśayā', ' G G L G G G G ')
AddSamavrtta('vilambitamadhyā', ' G G G L L G L L G G G ')
AddSamavrtta('acaṭu', ' L L L L L L L ')
AddSamavrtta('kṛtakavali', ' L L L L L L L L L L ')
AddSamavrtta('dorlīlā', ' L L G L L G L G G G G G ')
AddSamavrtta('kāmaśālā', ' G L G G L G G L G G L G G L ')
AddSamavrtta('valgā', ' G G L G G L G G L ')
AddSamavrtta('kaṁsari', ' G G G G L L ')
AddArdhasamavrtta('madākrāntā', ' L L G L L G L G L G L G G ', ' G G G L L G L G L G L G G G ')
AddSamavrtta('sarasī', ' L L L L G L G L L L G L L G L L G L G L G ')
AddSamavrtta('pūrṇā', ' G G L L G L G ')
AddSamavrtta('bhāratī', ' G G G G G G G G G G G ')
AddSamavrtta('mṛgendu', ' L G L ')
AddSamavrtta('sarojāvālī', ' L G G L G G G L G G L G ')
AddSamavrtta('sukhaśailam', ' G G G G L L G G L L G G ')
AddSamavrtta('kumāralalitā', ' L G L L L G G ')
AddSamavrtta('kamanī', ' L L G L G G ')
AddSamavrtta('anantadāmā', ' L L L L L L L L G L G L G G ')
AddArdhasamavrtta('kilikitā', ' G L G L L L G L G L G ', ' L L L G L L L G L G L G ')
AddSamavrtta('varajāpi', ' G L L L L G L ')
AddSamavrtta('tanvī', ' G L L G G L L L L L L G G L L G L L L L L L G G ')
AddSamavrtta('gajagatiḥ', ' L L L G L L L G ')
AddSamavrtta('vireki', ' G L G L L L G L G L ')
AddSamavrtta('sāhūti', ' G G G G G L ')
AddSamavrtta('pariṇāhī', ' G G G G L L L L G G L L G G ')
AddSamavrtta('vidhuravitānam', ' L L L L L L G L L L L G G ')
AddSamavrtta('gaṅgodakam', ' G L G G L G G L G G L G G L G G L G G L G G L G ')
AddArdhasamavrtta('korakitā', ' G L L G L L G L L G G ', ' L L L L G G L L L L G G ')
AddSamavrtta('indraḥ', ' L G L L G L L G G G ')
AddSamavrtta('upadhānam', ' L G L L L L L G L L G G ')
AddSamavrtta('pāñcālāṅghriḥ', ' L L L L G G G G ')
AddSamavrtta('bhujaṅgajuṣī', ' G L G L L G G L G L L G ')
AddSamavrtta('citibhṛtam', ' L L L L L L L G L G ')
AddSamavrtta('maṇimālā', ' G G L L G G G G L L G G ')
AddSamavrtta('viyogavatī', ' L G L L G L L L L L L G ')
AddSamavrtta('indravadanā', ' G L L L G L L L G L L L G G ')
AddSamavrtta('lulitam', ' L L G L L G L L G L ')
AddSamavrtta('māṇavakam', ' G L L G G L L G ')
AddArdhasamavrtta('upāḍhyam', ' G L L G L L G L G L G G ', ' L L L L L G L G L G G ')
AddSamavrtta('niśipālam', ' G L L L G L L L G L L L G L G ')
AddSamavrtta('viṣvagvitānam', ' G G L G L L L G L L L L G G L G G L G G ')
AddVishamavrtta('saurabhakam', ' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L G L L L G L L G ', ' L L G L G L L L G L G L G ')
AddSamavrtta('śraddharāntā', ' G L G G L G G L G G L G G ')
AddSamavrtta('hemahāsaḥ', ' G L G G L G G L G G ')
AddArdhasamavrtta('aupagavītam', ' G L L G L G G L G L G ', ' L L L G L G G L G L G ')
AddSamavrtta('amanā', ' L L G L L G L L ')
AddSamavrtta('pulakāñcitam', ' G L L L L G L L L L G G L L L L L L G L L G G ')
AddSamavrtta('vīvadhaḥ', ' L L L L G L L L G L G ')
AddSamavrtta('ulkābhāsaḥ', ' G G G G G L L L G G G G G ')
AddSamavrtta('kirātaḥ', ' L L L L G L G G L G G L G ')
AddSamavrtta('amānikā', ' L G L G L G G L ')
AddSamavrtta('dadhi', ' G L L G L L G L L ')
AddSamavrtta('gaṇadehā', ' L L G G G G L L G G ')
AddSamavrtta('vainasam', ' G L G L G ')
AddSamavrtta('alālāpi', ' L L G L G G L ')
AddSamavrtta('prasarā', ' G G G L L G L L G G ')
AddSamavrtta('bhūriśobhā', ' G G G G G G L L L L L L G G L G G L G G ')
AddSamavrtta('vabhrūḥ', ' G G L G G G ')
AddSamavrtta('kumbhāri', ' G G G G L ')
AddSamavrtta('arjitaphalikā', ' G L L L L G G L G L L G ')
AddSamavrtta('samāhitam', ' L L L L G L L G L L G L L G L L G L L G L L G G ')
AddSamavrtta('parabhṛtam', ' L L L G G L G ')
AddSamavrtta('pārthivam', ' L G L L L G L G L L L G L L L G L G ')
AddSamavrtta('visraṁsi', ' L L L L L G G G L L ')
AddVishamavrtta('śālā', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('hemarūpam', ' G L G G L G L G ')
AddSamavrtta('jaladarasitā', ' L L L L L G L G G L G G L G ')
AddSamavrtta('mālatikā', ' L G L L G L ')
AddSamavrtta('antarvikāsavāsakaḥ', ' G G L G L G L G L G L G ')
AddSamavrtta('phalinī', ' L L L L G G G L L G ')
AddSamavrtta('vasupadamañjarī', ' L L L L G L G L L L G L L G L G L G ')
AddSamavrtta('praharṣiṇī', ' G G G L L L L G L G L G G ')
AddSamavrtta('candralekhā', ' G G G G L L L L L L G G L G G L G G ')
AddSamavrtta('vāṭikāvikāśaḥ', ' G L L L L L L G G L G L G G ')
AddSamavrtta('madanayā', ' L L L L L L G G L L G ')
AddArdhasamavrtta('karabhoddhatā', ' G L L G G L G L G L G ', ' L L G L L L G L G L G ')
AddSamavrtta('vikalavakulavallī', ' L L L L L L G G L G G L ')
AddSamavrtta('mālādharaḥ', ' L L L L L G L G L L L G L G G L G ')
AddSamavrtta('kāṁsīkam', ' G G G L L L L G G ')
AddSamavrtta('upacitram', ' L L G L L G L L G L G ')
AddSamavrtta('subhadrikā', ' L L L L L L G L G L G ')
AddSamavrtta('vitānitā', ' L L L L L L L L L G L G L G ')
AddSamavrtta('kāmanibhā', ' G G G L L G G G L L ')
AddSamavrtta('indravajrā', ' G G L G G L L G L G G ')
AddSamavrtta('kuḍaṅgikā', ' L G L G L G L G L G L G L G ')
AddSamavrtta('toṭakam', ' L L G L L G L L G L L G ')
AddSamavrtta('paṇavaḥ', ' G G G L L L L G L G ')
AddSamavrtta('anukūlā', ' G L L G G L L L L G G ')
AddSamavrtta('vijohā', ' G L G G L G ')
AddSamavrtta('krīḍāyatanam', ' L L G L L G L L G G G L L G ')
AddSamavrtta('prapannapānīyam', ' G G L L G G G G L G L G G G ')
AddArdhasamavrtta('ālepanam', ' L L L G G L G G L G G L G ', ' L L L G L L L G G L G G L G ')
AddSamavrtta('dhṛtahālā', ' G G G G L L G G G ')
AddSamavrtta('parivṛḍham', ' L L L G G L G G L G G L G ')
AddArdhasamavrtta('dhīrāvarttaḥ', ' G G G G G L L G G L L G G ', ' G G G G L L L L G G G G G ')
AddSamavrtta('grāvāstaraṇam', ' G G G G L L L L G G L L G G G G L L G ')
AddArdhasamavrtta('upameyā', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('kṛṣṇagatikā', ' G L L L G L G G ')
AddSamavrtta('rādhikā', ' L L G G L L G L L G L G ')
AddSamavrtta('śiśubharaṇam', ' L L L L L L L L L L L L L L G G ')
AddSamavrtta('cārugatiḥ', ' L L L L L L L L G G G G L L L L G L G L G L G L G G ')
AddSamavrtta('kāmacāri', ' G G L G L L G L G L ')
AddSamavrtta('kanakaketakī', ' G G L L L G L G L L G L G ')
AddSamavrtta('sarasamukhī', ' G G L L L L L L G L ')
AddSamavrtta('salekhā', ' L L L L L L G G G L L L L L L G G ')
AddSamavrtta('bhadrakam', ' G L L G L G L L L L L G L L L G L G L L L G ')
AddSamavrtta('devalam', ' G G G L G G L ')
AddSamavrtta('vivaravilasitam', ' G G L L L L L L G G G G ')
AddSamavrtta('līlācandram', ' G G G G G G G G L L G G L L G ')
AddVishamavrtta('vāṇī', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('kaṭhināsthi', ' G L L L L L L G L ')
AddSamavrtta('añcalavatī', ' G L L L G L L G L G L L L G ')
AddSamavrtta('ahatiḥ', ' L G G L L L L ')
AddSamavrtta('vātyā', ' G L L L G G G G ')
AddSamavrtta('aśokapuṣpam', ' L L L L L L G L G L G L G ')
AddSamavrtta('krośapadā', ' G L L G G G L L G G L L L L L L L L L L L L L L G ')
AddArdhasamavrtta('padmāvatī', ' G G L G L L L G L L G G ', ' L L G L G L L L G L L G G ')
AddSamavrtta('vaṁśāropī', ' L G G G L L G G G G ')
AddSamavrtta('vidyādhāraḥ', ' G G G G G G G G G G G G ')
AddSamavrtta('nāsābharaṇam', ' G G L L G G G L L G G L L G ')
AddSamavrtta('halodgatā', ' L L L L G L G L G ')
AddSamavrtta('uddhatikarī', ' G L L L G G G G G G G ')
AddSamavrtta('hetiḥ', ' L L L L G L L G L G L L G L ')
AddSamavrtta('karṇasphoṭam', ' L L L L G G G G L L L L G G G G L ')
AddSamavrtta('bhaurikam', ' G L G G L G G L G ')
AddSamavrtta('kokapadam', ' G L L G G G L L G G L L L L L L L L L L L L G G ')
AddSamavrtta('sahajā', ' L L G L L G L G L G ')
AddSamavrtta('lalitāgamanam', ' L L G L L G L G G G G ')
AddSamavrtta('kalpadhāri', ' G L G G L G G L G L G L G L G L ')
AddSamavrtta('kāmarūpam', ' G G G G L G G L L L L L G G L G G ')
AddSamavrtta('celāñcalam', ' G G L G L L L L G L G L G G ')
AddSamavrtta('gambhāri', ' G L G G L G G L G G L ')
AddVishamavrtta('buddhiḥ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('viśadacchāyaḥ', ' L L G G G L L G G G ')
AddSamavrtta('kalki', ' G L G L L ')
AddSamavrtta('kaṇikā', ' G G L L G ')
AddSamavrtta('amati', ' G L L L L L ')
AddSamavrtta('cañcarīkāvalī', ' L G G G G G G L G G L G G ')
AddSamavrtta('hrīḥ', ' G L G G L ')
AddSamavrtta('arditam', ' G L L G L L G L L G L L G L L G L L L L L L G G ')
AddSamavrtta('kalpamukhī', ' G L L G G L G ')
AddSamavrtta('drutalambinī', ' L L G L L G L G L L G L G ')
AddSamavrtta('bimbam', ' L L L L L G L G G ')
AddVishamavrtta('rāmā', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('lasadasu', ' L L L L L G L G ')
AddSamavrtta('vyāhāri', ' G L L G G G L ')
AddArdhasamavrtta('dhīrāvarttaḥ', ' G G G G L L L L G G G G G ', ' G G G G G L L G G L L G G ')
AddSamavrtta('kalāpatiprabhā', ' G L G L G L G L G L G L G ')
AddArdhasamavrtta('camūrubhīruḥ', ' G L G L L L L G L G L G ', ' L L G L L L L G L G L G G ')
AddSamavrtta('suṣamā', ' G G L L G G G L L G ')
AddSamavrtta('hrīṇahaiyaṅgavīnam', ' G L G G L G G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('aḍamaruḥ', ' L L L L L L L L L L L L L ')
AddSamavrtta('kulādhārī', ' L G G G L G G G ')
AddSamavrtta('aparājitā', ' L L L L L L G L G L L G L G ')
AddSamavrtta('keram', ' G L G G L L G L L G ')
AddSamavrtta('mauktikadāma', ' L G L L G L L G L L G L ')
AddSamavrtta('mahonmukhī', ' G G G L G L G ')
AddSamavrtta('saṁhatikā', ' L L G L G L L G L G ')
AddSamavrtta('asudhārā', ' L G L G L G G L G L G G ')
AddSamavrtta('vinayavilāsaḥ', ' L L L L G G L L L L G G L L L L G G L L L L G G G G ')
AddSamavrtta('subhadrāvataraṇiḥ', ' G G G G G L G G L L L G ')
AddArdhasamavrtta('akoṣakṛṣṭā', ' L L G G L L G L G L G L G G ', ' G G L L G L G L G G ')
AddSamavrtta('ayamitam', ' L L L G L L ')
AddSamavrtta('sārasanāvaliḥ', ' L L L G L L L G L L G L G ')
AddSamavrtta('śantanu', ' G L L G G L L ')
AddSamavrtta('kārpikā', ' G L G L G L L ')
AddSamavrtta('amālīnam', ' L G G L G G G G G G G ')
AddSamavrtta('sumohitā', ' L G L G G G G ')
AddSamavrtta('cittacintāmaṇiḥ', ' G L G G L G G L G L L L L G L G G L G G L G G L G ')
AddSamavrtta('vāntabhāraḥ', ' L L L G G L G G ')
AddSamavrtta('paddhari', ' L G G G G L L ')
AddSamavrtta('arilā', ' L L G G L L G L L G L L ')
AddSamavrtta('mattebhavikrīḍitam', ' L L G G L L G L G L L L G G G L G G L G ')
AddSamavrtta('mattālī', ' G G G G G L L G G G G G ')
AddSamavrtta('amatiḥ', ' G G G L L L L ')
AddSamavrtta('kāmukalekhā', ' G L L G G G L L G G L ')
AddSamavrtta('mṛṣṭapādā', ' G L G G G L G ')
AddSamavrtta('piculam', ' L L G L L G L G L G L ')
AddSamavrtta('abhikhyā', ' L L G G G G ')
AddSamavrtta('bhūrighaṭakam', ' G G G L L L G G G G G ')
AddSamavrtta('rathoddhatā', ' G L G L L L G L G L G ')
AddSamavrtta('śaṅkāvalī', ' G G L G L L G L G L L L L L G ')
AddSamavrtta('kāsāram', ' G G G G G G G G L L L L G G L L G ')
AddSamavrtta('vāṇīvāṇaḥ', ' G G G G L L L L G G L L G G L L G G G G ')
AddSamavrtta('kumāragatiḥ', ' L G L L L L G L L L L G ')
AddSamavrtta('paricāravatī', ' G G L G L L G L L G ')
AddSamavrtta('vāhāntaritam', ' G G L L L L G L L G L L L L L L G ')
AddSamavrtta('sūtaśikhā', ' G G L L G G L L G G L L L L G G ')
AddSamavrtta('āpaṇikā', ' L G L G G L L G L L G L G ')
AddSamavrtta('vallavīvilāsaḥ', ' G L G L G G L G G G G ')
AddSamavrtta('kulyāvarttam', ' G G G G G G L L G G L L G G L L ')
AddSamavrtta('manthari', ' G G G L G G L L ')
AddSamavrtta('madanoddhurā', ' G L L G L L G L G ')
AddSamavrtta('bhadrikā', ' G L G L L L G L G ')
AddSamavrtta('jhillīlīlā', ' L L L L G G G G G G G G L G L G G G G ')
AddArdhasamavrtta('paraprīṇitā', ' L L L L L L G G L G G L G ', ' L L L L L L L L G G G L G G L G ')
AddSamavrtta('paurasari', ' G L L G L L L ')
AddSamavrtta('śārdūlalalitam', ' G G G L L G L G L L L G G G L L L G ')
AddSamavrtta('kalpamīlitā', ' G L G G L G G L G G L G L G ')
AddSamavrtta('amoghamālikā', ' L G L G L G L G G G G ')
AddSamavrtta('nīpavanīyakam', ' G L L L L L L L L L L G G L L L L G L L G L L G G ')
AddSamavrtta('saṅgamavatī', ' G L L L G L L L L L L G ')
AddSamavrtta('abhidhātrī', ' L L G L L G L L G L G L G L G G ')
AddArdhasamavrtta('alparutam', ' G L L L L L L G L L G L L ', ' G L L L L L L G G L L L L ')
AddVishamavrtta('premā', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('tanimā', ' L L L L L L L L G G ')
AddSamavrtta('śobhā', ' L G G G G G L L L L L L G G L G G L G G ')
AddSamavrtta('valīkendu', ' L L G G L G G L ')
AddSamavrtta('aśaniḥ', ' L L L L L L G G L L L L L ')
AddSamavrtta('mahanīyā', ' L G G L L G G ')
AddSamavrtta('kalanāyikā', ' L G L G G L L L L L G L G ')
AddSamavrtta('upodari', ' L G L L G L L ')
AddSamavrtta('mālavikā', ' G G L L G L L L G L G ')
AddSamavrtta('bodhāturā', ' L G G G G G L G G G ')
AddSamavrtta('mudiram', ' L L G L L G L L G L L G L L G L L G L L G L L G G ')
AddSamavrtta('paṭu', ' L L L L ')
AddSamavrtta('vidyadālī', ' L G G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('saurabhi', ' G L L L L G ')
AddArdhasamavrtta('vegavatī', ' L L G L L G L L G G ', ' G L L G L L G L L G G ')
AddSamavrtta('rudrālī', ' L L L L L G G G ')
AddSamavrtta('daṇḍī', ' G G L L L L G G L L L L G G L L L G ')
AddSamavrtta('keśavatī', ' L G G G L L G ')
AddArdhasamavrtta('āsavavāsitā', ' L L L G L L L G L G L G L G G ', ' L L G G L L G L G L G L L L G G ')
AddSamavrtta('krośitakuśalā', ' G L L L L G L L G G G ')
AddSamavrtta('kīṭamālā', ' L L G L G L G G L ')
AddSamavrtta('vindu', ' L G G G G L ')
AddVishamavrtta('ramaṇā', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddArdhasamavrtta('anirayā', ' L L L G L L L L G L G L G ', ' L L L G L L L G L L G L G ')
AddSamavrtta('anāmayam', ' L G L L G L L G L L G L L G L L G L L G L L G L ')
AddArdhasamavrtta('kāntā', ' G G G L L G L G L G G ', ' G G L L G L G L G G ')
AddSamavrtta('nirmedhā', ' L L L G G L G G G G ')
AddSamavrtta('surasā', ' G G G G L G G L L L L L L G G L L L G ')
AddSamavrtta('kāmā', ' G G L L L L L G G ')
AddSamavrtta('kāladhvānam', ' G G G G G G L L L L G G G G ')
AddSamavrtta('valvajam', ' G L L G L L G G L L L L L L G G G ')
AddArdhasamavrtta('alipadam', ' G L G G L G L L L G G L G ', ' L L L G G L G G L G ')
AddSamavrtta('nālī', ' L G G G G ')
AddSamavrtta('pāñcāli', ' G G L ')
AddArdhasamavrtta('upāḍhyam', ' L L L L L G L G L G G ', ' G L L G L L G L G L G G ')
AddSamavrtta('varatrā', ' G L L L G L L G L L G G ')
AddVishamavrtta('lalitam', ' L L G L G L L L G L ', ' L L L L L G L G L G ', ' L L L L L L L L G L L G ', ' L L G L G L L L G L G L G ')
AddSamavrtta('valīmukhī', ' L G L G L G ')
AddVishamavrtta('ṛddhiḥ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('avanijā', ' L G L L G L G L G ')
AddSamavrtta('ākhrṭam', ' G L G L G L L L ')
AddSamavrtta('damanakam', ' L L L L L L L L L L G ')
AddArdhasamavrtta('samayavatī', ' G G L L L L G G L L G ', ' L L G G G G L L L L G ')
AddSamavrtta('akhaṇḍamaṇḍanam', ' L G L G L G G L G L G L G ')
AddSamavrtta('vyākośakośalam', ' G G L G L L L G G G L L L L G L L G L L G L G L G ')
AddVishamavrtta('bālā', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ')
AddSamavrtta('khaṭakā', ' L G L L G L L G L L G ')
AddSamavrtta('harit', ' L L L L L G G L ')
AddArdhasamavrtta('ghaṭikā', ' G G L L L G L G L G ', ' L L G L L G L G L G ')
AddSamavrtta('viralam', ' G L L L L G G L L G ')
AddSamavrtta('śritakamalā', ' G L L G L L L L G G G ')
AddSamavrtta('śravaṇābharaṇam', ' L L L L G L L G L L G L L G L L G L L G L L G ')
AddSamavrtta('kalahakaram', ' L L L L L L L L L L L L G L L G ')
AddArdhasamavrtta('vāsavavāsinī', ' L L L L G L G L L L G L L G L G ', ' G G L L G L G L L L G L L G L G ')
AddSamavrtta('ratirekha', ' G G L L G G G L L G L L G G ')
AddSamavrtta('vimalā', ' L L G L L G L G L G G ')
AddSamavrtta('staradhi', ' L G L G L L L ')
AddSamavrtta('chalitakam', ' L L L G G L G L L G ')
AddArdhasamavrtta('anālepanam', ' L L L G L L L G G L G G L G ', ' L L L G G L G G L G G L G ')
AddArdhasamavrtta('lāsyalīlā', ' G L L L L G G G L G G L G G ', ' G G L L G G G L G G L G G ')
AddSamavrtta('atikali', ' G G L L L L ')
AddSamavrtta('taḍidambaram', ' G L L G L L G L L G L L G L L G L L G L L ')
AddSamavrtta('ārabhaṭī', ' G L L G L L L L L L G L L G G G ')
AddSamavrtta('maulimālikā', ' G L G L G G G G ')
AddSamavrtta('dhāri', ' G L G L ')
AddSamavrtta('viśālāmbhojālī', ' G G L L L G L G G G G G ')
AddSamavrtta('karaśayā', ' L L L G L L G L G ')
AddSamavrtta('citram', ' G L G L G L G L G L G L G L G L ')
AddSamavrtta('udāttahāsaḥ', ' L G L G G L G L L L G L G ')
AddSamavrtta('siktamaṇimālā', ' G L L L G G G G L L G G ')
AddSamavrtta('vikacavatī', ' L L L L G G G L L ')
AddSamavrtta('undari', ' G L L L G L G ')
AddSamavrtta('vibhā', ' L L L L G G G G L L G G G ')
AddSamavrtta('talpakatallajam', ' G L L G L L G L L G L L G L L L G L G G G ')
AddSamavrtta('nandi', ' G L L G L L ')
AddSamavrtta('dāmaghaṭitā', ' L L L L L L G L L L G ')
AddSamavrtta('babhrulakṣmīḥ', ' G L G G L G G G L G G L G G ')
AddArdhasamavrtta('amarāvatī', ' G L G L G L G L G L G L ', ' L G L G L G L G L G L G G ')
AddVishamavrtta('udgatā', ' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L L L L L L G L L G ', ' L L G L G L L L G L G L G ')
AddSamavrtta('guñjā', ' G G L L G G L ')
AddSamavrtta('kṣut', ' G L L L L ')
AddSamavrtta('śivikā', ' G L L G L L G L L G L L G L L G L L G L L G L L G ')
AddSamavrtta('lumbākṣī', ' L L G L L G L L L G G G ')
AddSamavrtta('maṇihaṁsaḥ', ' L L G L G L L G L G L L G L G ')
AddArdhasamavrtta('mārdaṅgī', ' G G G L L L L G L L L L L L L L G G ', ' L L G L L L L L G L L L G G ')
AddSamavrtta('rambhā', ' G G L L L L G G G ')
AddSamavrtta('bhujaṅgaprayātam', ' L G G L G G L G G L G G ')
AddSamavrtta('prahāṇaḥ', ' L G G G G G G ')
AddSamavrtta('rasadhāri', ' L L G L G G G ')
AddVishamavrtta('śīlāturā', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('mattā', ' G G G G L L L L G G ')
AddSamavrtta('kiraṇakīrttiḥ', ' G G L L G L G G L G L L L L L L L G G ')
AddSamavrtta('rasikaparicitā', ' L L G G G L L L L L L G ')
AddSamavrtta('niryatpārāvāraḥ', ' G G G G G L G G L G G L G G ')
AddSamavrtta('saṁbhṛtaśaradhiḥ', ' G L L L L L L G G G L L L L L L G G L L G G L ')
AddSamavrtta('hoḍapadā', ' G L L G L G G ')
AddSamavrtta('bhīmārjanam', ' G G L G L G G ')
AddSamavrtta('śāyinī', ' L L L L L G L G L G L L L G L G G ')
AddSamavrtta('mauralikam', ' G L L G L L G ')
AddSamavrtta('lāsyakārī', ' G L G G L G G L G G L G G L G ')
AddSamavrtta('bhāvinīvilasitam', ' G L G L L L G L G L L L G L G L L L G L G L L L G ')
AddSamavrtta('varddhiṣṇu', ' G G L G G G L ')
AddSamavrtta('mayūrasāriṇī', ' G L G L G L G L G G ')
AddSamavrtta('valā', ' G L L G ')
AddSamavrtta('sarojavanikā', ' L G L L L G L G L G G ')
AddSamavrtta('meghadhvanipūraḥ', ' G G L L G G G G G G G ')
AddSamavrtta('viśeṣakabalitam', ' L L L L L L G G G G G G L G L L G L L G L L L L G ')
AddSamavrtta('dhanadhari', ' L L G L L L L ')
AddSamavrtta('siṁhapuccham', ' L G G L G G L G G L G G L G G ')
AddSamavrtta('haravanitā', ' L L L L L L L L L L L L G ')
AddSamavrtta('dārudehā', ' G L G G L G G L G G G ')
AddArdhasamavrtta('īhā', ' L L L L G L L G L L G G ', ' G L L G L L G L L G G ')
AddSamavrtta('pramodaḥ', ' L L L L L L G L G G L G G ')
AddArdhasamavrtta('vāsinī', ' G G L L G L G L L L G L L G L G ', ' L L L L G L G L L L G L L G L G ')
AddSamavrtta('moṭanakam', ' G G L L G L L G L L G ')
AddSamavrtta('pramitākṣarā', ' L L G L G L L L G L L G ')
AddSamavrtta('paritoṣā', ' L L G L L L L G L L G G ')
AddSamavrtta('nirudam', ' L L G L L L L L ')
AddArdhasamavrtta('atailam', ' L G L G G L G G L G ', ' G G L G G L G G L G ')
AddSamavrtta('arpitamadanā', ' G L L L L G L L L L G G ')
AddSamavrtta('vanitāvilokaḥ', ' G G L G G L L L G L G G ')
AddSamavrtta('sārddhapadā', ' G L G L G G L L G L G L G ')
AddSamavrtta('dīpakam', ' G L L G G L L L L G G L L G G ')
AddSamavrtta('guṇavatī', ' L L L G G G ')
AddArdhasamavrtta('rucimukhī', ' L L L L L L L L G L L G G ', ' L L L L L L G L L L L G G ')
AddSamavrtta('sulūḥ', ' L L L L G ')
AddSamavrtta('mañjīrā', ' G G G G G G G L L G G G L L G G G G ')
AddSamavrtta('vidrumadolā', ' L L L L G G G G L L G G ')
AddSamavrtta('mānavatī', ' L G L L G L L G L L G L L G L L G L L G L L G ')
AddArdhasamavrtta('vimāninī', ' L L G G L L G L G L G ', ' G G G L L L L G L G L G ')
AddSamavrtta('paridhānīyam', ' L L L L L L G L L G G L L G L L G G L L G G G ')
AddSamavrtta('muhurā', ' L L G L G L L ')
AddSamavrtta('śarameyā', ' L L G G L L L G L L G G ')
AddSamavrtta('mahī', ' L G ')
AddArdhasamavrtta('pramālikā', ' L L G G L L G L G L G G ', ' L L G L L G L G L G G ')
AddSamavrtta('praguṇam', ' L L G G G ')
AddVishamavrtta('vāsantikā', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ')
AddSamavrtta('śaśikalā', ' L L L L L L L L L L L L L L G ')
AddSamavrtta('līlāratnam', ' G G G G G G L L G G G G ')
AddSamavrtta('gahvaram', ' G L G G L G G L G L G ')
AddSamavrtta('abhrabramaṇam', ' G G L L L L G G G L L G L L L L L L L L L L L L G ')
AddSamavrtta('priyaṁvadaḥ', ' L L L G L L L G L G L G ')
AddSamavrtta('snu', ' ल ')
AddSamavrtta('vilulitavanamālā', ' L L L L L L G G G L L L L L L G G G ')
AddSamavrtta('parviṇī', ' L L L L L L G L G L L L G L G G L G ')
AddSamavrtta('atiraṁhaḥ', ' L G L L G L L G L G L G G ')
AddVishamavrtta('upasthitapracupitam', ' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L L L L G ', ' L L L L L L L L L L G L L G G ')
AddSamavrtta('vīṇādaṇḍam', ' L G L L L G L G G G G G ')
AddSamavrtta('lolalolambalīlam', ' G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('svaravarṣiṇī', ' L L G L G L L G L G G G ')
AddSamavrtta('svanakarī', ' L L L G L L G ')
AddSamavrtta('ravonmukhī', ' G G L L G L G L G ')
AddSamavrtta('śāntasurabhiḥ', ' G L L L L L G L G L L G L L G ')
AddSamavrtta('suvṛttiḥ', ' L L G L L L L L L G G ')
AddSamavrtta('naragā', ' L L L L G G L L G G ')
AddSamavrtta('upendravajrā', ' L G L G G L L G L G G ')
AddSamavrtta('virājikarā', ' L G L L G G G G ')
AddVishamavrtta('kīrtiḥ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('cārvaṭakam', ' G G G G L L G L L G G G G G G ')
AddSamavrtta('murajikā', ' L L L G G L L ')
AddSamavrtta('saṁsṛtaśobhāsāraḥ', ' L L G G G L L G G G G ')
AddSamavrtta('nāndīmukhī', ' L L L L L L G G L G G L G G ')
AddSamavrtta('aśvagatiḥ', ' G L L G L L G L L G L L G L L L L G ')
AddSamavrtta('vṛttahāri', ' L G G L G L ')
AddSamavrtta('viratimahatī', ' G G L L L L L L L L G G ')
AddSamavrtta('īhāmṛgī', ' G G L G L L G G L G G ')
AddSamavrtta('nīrāñjaliḥ', ' G G L L L L G G L G ')
AddSamavrtta('hīrakahāradharam', ' G L L G L L G L L G L L G L L G L L ')
AddSamavrtta('nirasikā', ' L L L G L G ')
AddSamavrtta('sphuṭaghaṭitā', ' L L L L G G L L L ')
AddSamavrtta('mālīnam', ' G G G L L ')
AddSamavrtta('kāru', ' L L G L ')
AddSamavrtta('priyajīvitam', ' G L L G L L G L L G L L G L L G L L G L L G L L G G ')
AddSamavrtta('pañcaśikhā', ' L L G L L G G G ')
AddSamavrtta('uditavijohā', ' G G L G G L L L L G G ')
AddArdhasamavrtta('sammadākrāntā', ' G G G L L G L G L G L G G G ', ' L L G L L G L G L G L G G ')
AddSamavrtta('dodhakam', ' G L L G L L G L L G G ')
AddSamavrtta('dhṛṣṭapadam', ' G L L G L L L G L L G G ')
AddSamavrtta('kurucarī', ' G L G G L L L G ')
AddSamavrtta('śephālī', ' L G G G G G G G G G ')
AddSamavrtta('anibhṛtam', ' L L L G G L ')
AddSamavrtta('chalitakapadam', ' G G L L L L L G L L G G ')
AddSamavrtta('vakrāvalokaḥ', ' L L L L L L G G G G L G G L G G ')
AddSamavrtta('sambuddhiḥ', ' L L G G G L L G G ')
AddSamavrtta('śampā', ' G G L L L L G G G G G G ')
AddSamavrtta('anirbhāraḥ', ' L G G G G G G G ')
AddSamavrtta('vahirvali', ' L G L L G L G ')
AddSamavrtta('śambhuḥ', ' L L G G G L L G G G L L G G G G G G G ')
AddSamavrtta('svinnaśarīram', ' G L L G G L G G L G G L G ')
AddSamavrtta('bhūrimadhu', ' G G G G L L L ')
AddSamavrtta('nirgalitamekhalā', ' L L L L L L G L G L L L G L L L G L G ')
AddSamavrtta('hāriṇī', ' G G G G L L L L L L G G L G G L G ')
AddSamavrtta('abhirāmā', ' L L G G L L G G L L L L G ')
AddSamavrtta('śaragītiḥ', ' G L G L L G G ')
AddSamavrtta('śrīḥ', ' गु ')
AddSamavrtta('mātrā', ' G G G L L L L L L G G ')
AddSamavrtta('bhogāvalī', ' G G L G L L G L G L L G L L L L L L L G L G ')
AddArdhasamavrtta('vasantamālikā', ' L L G L L G L G L G G ', ' L L G G L L G L G L G G ')
AddSamavrtta('jihmāśayā', ' G G L G L L L G L L G ')
AddSamavrtta('rājarājī', ' G G L G G L G ')
AddSamavrtta('kanakakāminī', ' L G L G G L L L G L G ')
AddSamavrtta('mayūvadanā', ' G L L L G L L G L G L L G L G ')
AddSamavrtta('śikhariṇī', ' L G G G G G L L L L L G G L L L G ')
AddSamavrtta('ānaddham', ' G L G L L L L L G G G L G G G ')
AddSamavrtta('mahoddhatā', ' L G G L G L G ')
AddArdhasamavrtta('madhuvāri', ' L L G L G L L L G L G L G ', ' G G L G L L G L G L L G L ')
AddSamavrtta('sukhakārikā', ' L L G L G L L G L G G G L ')
AddSamavrtta('kāmoddhatā', ' G G L G G L L ')
AddArdhasamavrtta('kilikitā', ' L L L G L L L G L G L G ', ' G L G L L L G L G L G ')
AddSamavrtta('mṛdukīlā', ' L L G G L G ')
AddSamavrtta('ramaṇaḥ', ' L L G ')
AddSamavrtta('kareṇuḥ', ' G L G G G G ')
AddArdhasamavrtta('camūruḥ', ' L L G L L L L G L G L G G ', ' G L G L L L L G L G L G ')
AddSamavrtta('khagatiḥ', ' G L L G L L G L L G L L G L L G ')
AddSamavrtta('bhogāvaliḥ', ' G G L L L L L L L L G G L L G G ')
AddSamavrtta('candrikā', ' L L L L L L G G L G G L G ')
AddSamavrtta('nārācam', ' L L L L L L G L G G L G G L G G L G ')
AddSamavrtta('śilīmukhojjṛmbhitam', ' G G G L L G L G L L L L L G L G G L G ')
AddSamavrtta('kanyā', ' G G G G ')
AddSamavrtta('vasumatī', ' G G L L L G ')
AddSamavrtta('kalitakamalavilāsaḥ', ' L L L L L L G G G G G ')
AddSamavrtta('nīrāntikam', ' G G L G L L L G L L G G ')
AddArdhasamavrtta('sārikā', ' G L G L L L G L G L G ', ' G L G L L L G L L G G ')
AddSamavrtta('manolā', ' L G G L L G G G ')
AddSamavrtta('lalitalalāma', ' L L L L G L G G L G G L G G L G G L L L G ')
AddSamavrtta('vijayaparicayā', ' L L L L L L G G L L G G ')
AddArdhasamavrtta('mṛdumālatī', ' L L L L G L L G L G L G ', ' L L L L L L G L G L G ')
AddSamavrtta('mandākṣamandaram', ' L L L L L L G G G G G G L G L G L G G G G ')
AddSamavrtta('parikhāyatanam', ' L L G L L G L L G G L L L L G G ')
AddSamavrtta('śarat', ' L L L G L L G L L G ')
AddSamavrtta('yaśaskarī', ' L G L G L G G G ')
AddSamavrtta('viśikhalatā', ' L L L L G L G L G G L G ')
AddArdhasamavrtta('surāḍhyā', ' L L L L L L G L G L G G ', ' G G G L L G L G L G G ')
AddSamavrtta('bhāskaram', ' G L L L L L L G L L G G G L L L L L L L L L L G G ')
AddSamavrtta('nīhārī', ' G G G G G G L ')
AddSamavrtta('rāḍhi', ' G L L G G L ')
AddArdhasamavrtta('ālolaghaṭikā', ' L L G L L G L G L G ', ' G G L L L G L G L G ')
AddSamavrtta('kalā', ' L G L G ')
AddSamavrtta('lavalīlatā', ' G L L G L G L L L G L L G ')
AddSamavrtta('kāraviṇī', ' G L L L G L G L L L G L L G ')
AddSamavrtta('hīram', ' G G L L L L G ')
AddSamavrtta('bimbālakṣyam', ' G G G G L G G G L G G L G G ')
AddSamavrtta('pārāvāraḥ', ' G G L L L L L L L L G G G G ')
AddSamavrtta('praphullakadalī', ' L G L L L G G G G G G ')
AddArdhasamavrtta('ayavatī', ' L L G G G G L L L L G ', ' G G L L L L G G L L G ')
AddSamavrtta('mīnapadī', ' G L L G L G L ')
AddSamavrtta('surayānavatī', ' L L G L L G G L L G ')
AddSamavrtta('kumbhodhnī', ' G G G G L L L G L L G G ')
AddSamavrtta('muśaki', ' G G L L L L L ')
AddSamavrtta('bhūmadhārī', ' L G G L G G G G ')
AddVishamavrtta('jāyā', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ')
AddSamavrtta('vāṇībhūṣā', ' G G G G G G G G L L L L G G G ')
AddSamavrtta('virodhinī', ' L L L G L L L L G L G L G ')
AddArdhasamavrtta('bhujaṅgabhṛtā', ' L L G L L G L L G L L G G ', ' G L L G L L G L L G L L G ')
AddSamavrtta('śambaradhārī', ' G L L G G L L G G ')
AddSamavrtta('camarīcaram', ' L L L L L L G L G L L L G L G ')
AddSamavrtta('vihāriṇī', ' L L G L G L G G L G G ')
AddSamavrtta('māyāsārī', ' L L L L G G G G G ')
AddArdhasamavrtta('pramodapadam', ' L L L L G L L G L G L L L G G ', ' L L L L L L G L G L G L G G ')
AddSamavrtta('sudāyi', ' L G L L L L ')
AddSamavrtta('kiṁśukāstaraṇam', ' G L G L L G L G G G G G ')
AddSamavrtta('phalguḥ', ' L L G G L L L L G G L L L L G G L ')
AddSamavrtta('pārāvataḥ', ' G G L G G L G G L G G L G ')
AddArdhasamavrtta('atisurahitā', ' G G L L L L L L L L L L G ', ' L L L L L L L L G L L G G ')
AddSamavrtta('sammadavadanā', ' G L L G L L G L L L L G ')
AddSamavrtta('viśālaprabham', ' L G L G G L G G L G ')
AddSamavrtta('vanitābharaṇam', ' G L L G L L L L G L L G ')
AddSamavrtta('malayasurabhiḥ', ' G G G L L L L L L G G G ')
AddSamavrtta('galitanālā', ' L G L G L L L G G G L G ')
AddSamavrtta('saurakāntā', ' G L G G L L G ')
AddSamavrtta('bhujaṅgavijṛmbhitam', ' G G G G G G G G L L L L L L L L L L G L G L L G L G ')
AddSamavrtta('akahari', ' L L L L L L L L L L L L L L ')
AddSamavrtta('ardhakṣāmā', ' G G G G G L L G G ')
AddSamavrtta('kāsārakrāntā', ' G G G G G L L G L L G G ')
AddSamavrtta('tārakam', ' L L G L L G L L G L L G G ')
AddSamavrtta('uditadineśaḥ', ' L L G L L L L G G G G ')
AddSamavrtta('pratāritā', ' L L G L L L G L G L G ')
AddSamavrtta('nardaṭakam', ' L L L L G L G L L L G L L G L L G ')
AddSamavrtta('lolam', ' G G L G G ')
AddSamavrtta('dṛptadehā', ' L G G G L G G G L G G L G G ')
AddSamavrtta('dhaunikam', ' G L L L L L L L G ')
AddSamavrtta('pratimā', ' L L G L L G L L G L L G L L G L L G L L G ')
AddSamavrtta('parāmodaḥ', ' L G G L L G L L G L G L L L L G G G ')
AddSamavrtta('dhoritam', ' G L L L L L G L G G L G L L G ')
AddSamavrtta('kharakarā', ' L L L G L G G ')
AddSamavrtta('garuḍarutam', ' L L L L G L G L L L G L G G L G ')
AddSamavrtta('karabhit', ' L L G L L G G ')
AddSamavrtta('sāriṇī', ' G L G L L L G L G L L L G L G ')
AddSamavrtta('acaladhṛtiḥ', ' L L L L L L L L L L L L L L L L ')
AddSamavrtta('sumukhī', ' L L L L G L L G L L G ')
AddArdhasamavrtta('śukāvalī', ' G G L L G L G L G G ', ' G G G L L L L G L G L G G ')
AddSamavrtta('ītiḥ', ' G L L L G G ')
AddSamavrtta('nibhālitā', ' L L G G G L G L G ')
AddSamavrtta('śarakalpā', ' L L L L L L L L G L L L L G G ')
AddSamavrtta('rathapadam', ' L L L L L L L L G G G ')
AddSamavrtta('kacchapī', ' L G G G L G ')
AddArdhasamavrtta('bṛhaccharāvatī', ' L L G G L L L L L L G L G L G ', ' L L L L L L G L G L G G ')
AddSamavrtta('padyā', ' L G L G G G G ')
AddSamavrtta('śārdūlavikrīḍitam', ' G G G L L G L G L L L G G G L G G L G ')
AddSamavrtta('priyatilakā', ' G L L G L L L L G ')
AddSamavrtta('sahelikā', ' L G L G L L G L G ')
AddSamavrtta('vilāsavāsaḥ', ' G L L L L G G L L G L L L L G L G L G L L G G ')
AddSamavrtta('mugdham', ' G G G L ')
AddSamavrtta('kaṇṭhī', ' L G L G G ')
AddSamavrtta('cāmaram', ' G L G L G L G ')
AddSamavrtta('kaṁsāsāri', ' L G G G G G L ')
AddSamavrtta('methikā', ' G L G L L G L ')
AddSamavrtta('paṅktiḥ', ' G L L G G ')
AddSamavrtta('hemamihikā', ' G L L L G L L G L G L L G L ')
AddSamavrtta('śuddhāntam', ' L L L L L L L L G G G G ')
AddArdhasamavrtta('vilāsavāpī', ' G G L L G L G L G G ', ' L L G G L L G L G L G L G G ')
AddArdhasamavrtta('navanīlatā', ' L L G L L G L G L G ', ' L L G G L L L G L G L G ')
AddSamavrtta('upalekhā', ' L L G G L L L L L G L G ')
AddSamavrtta('kālasāroddhataḥ', ' L G L G G L L G L L L G L G G L G ')
AddSamavrtta('carapadam', ' L L L G G L G G L G ')
AddSamavrtta('maṇimukhī', ' L L L G L G L ')
AddSamavrtta('śilā', ' L G L L G ')
AddSamavrtta('ṛṣabhagajavilasitam', ' G L L G L G L L L L L L L L L G ')
AddVishamavrtta('puṣṭidā', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ')
AddSamavrtta('sukhelā', ' L L G L G L G L G G ')
AddArdhasamavrtta('añcitāgrā', ' L L L L G L L G L G L G G ', ' L L L L L L G L G L G G ')
AddSamavrtta('virahavirahasyam', ' G G G L L L L L L G G L L G G L L L L L L L L G G ')
AddSamavrtta('meghavisphūrjitā', ' L G G G G G L L L L L G G L G G L G G ')
AddSamavrtta('kākiṇikā', ' L G L L G L G L L L G L L G ')
AddSamavrtta('hariṇaplutam', ' G G G L L G L G L L G L G L L G L G ')
AddSamavrtta('kandavinodaḥ', ' G L L G G G L L G G G ')
AddSamavrtta('māṇavikāvikāṣaḥ', ' G G L G L L G L L G L G G ')
AddSamavrtta('vasantatilakā', ' G G L G L L L G L L G L G G ')
AddArdhasamavrtta('śarāvatī', ' L L L L L L G L G L G G ', ' L L G G L L L L L L G L G L G ')
AddSamavrtta('krīḍitakaṭakā', ' G L L L L G L L G G G G G G G ')
AddSamavrtta('senikā', ' G L G L G L G L G L G ')
AddSamavrtta('surākṣī', ' L L L L G G L G G G ')
AddSamavrtta('kaṅkaṇakvāṇavāṇī', ' G G G G L G G L G G L G G L G G L G G L G G ')
AddSamavrtta('varmitā', ' G L G L G L L G L G ')
AddSamavrtta('śālinī', ' G G G G G L G G L G G ')
AddArdhasamavrtta('viyadvāṇī', ' G G G L L G L G L G G G ', ' L L G G L L G L G L G G ')
AddSamavrtta('kusumbhinī', ' L G L G L L L L G L G L G G ')
AddSamavrtta('baladhārī', ' L L G G L L L L G G ')
AddSamavrtta('pratīhāraḥ', ' G L G G L G G L G G L G G L G G L ')
AddSamavrtta('prapātaḥ', ' L G G L G G L G G L G G L G ')
AddSamavrtta('upahitacaṇḍī', ' L L G G L L L L G G G ')
AddSamavrtta('maṇimadhyam', ' G L L G G G L L G ')
AddSamavrtta('madhyādhārā', ' G G G G L L G G G G ')
AddSamavrtta('tūṇakam', ' G L G L G L G L G L G L G L G ')
AddSamavrtta('tanukilakiñcitam', ' G G G G G G G G G L L L L G L L L L G G L L G G G G ')
AddSamavrtta('acalaviratiḥ', ' L L L L L L L L L L L L L L L L L L L L L G ')
AddSamavrtta('vanitāvinodi', ' L L L G L L G L G L ')
AddSamavrtta('dhavalam', ' L L L L L L L L L L L L L L L L L L G ')
AddSamavrtta('paripoṣakam', ' L L G L L G L L G L L G L L G L L G ')
AddSamavrtta('nīlā', ' G G L L L L G L G L G ')
AddSamavrtta('khaurali', ' L L L L G G G G L L ')